# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(835, 605)
        widget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textEdit_recv = QtWidgets.QTextEdit(widget)
        self.textEdit_recv.setGeometry(QtCore.QRect(9, 9, 581, 391))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.textEdit_recv.setFont(font)
        self.textEdit_recv.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit_recv.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit_recv.setReadOnly(True)
        self.textEdit_recv.setObjectName("textEdit_recv")
        self.Serial = QtWidgets.QGroupBox(widget)
        self.Serial.setGeometry(QtCore.QRect(599, 9, 231, 110))
        self.Serial.setObjectName("Serial")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Serial)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.toolButton = QtWidgets.QToolButton(self.Serial)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_4.addWidget(self.toolButton, 1, 3, 1, 1)
        self.pushButton_refresh = QtWidgets.QPushButton(self.Serial)
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.gridLayout_4.addWidget(self.pushButton_refresh, 1, 4, 1, 1)
        self.lsport = QtWidgets.QLabel(self.Serial)
        self.lsport.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lsport.setObjectName("lsport")
        self.gridLayout_4.addWidget(self.lsport, 0, 0, 1, 1)
        self.cbsbaud = QtWidgets.QComboBox(self.Serial)
        self.cbsbaud.setEditable(True)
        self.cbsbaud.setInsertPolicy(QtWidgets.QComboBox.InsertBeforeCurrent)
        self.cbsbaud.setObjectName("cbsbaud")
        self.cbsbaud.addItem("")
        self.cbsbaud.addItem("")
        self.cbsbaud.addItem("")
        self.cbsbaud.addItem("")
        self.cbsbaud.addItem("")
        self.cbsbaud.addItem("")
        self.cbsbaud.addItem("")
        self.cbsbaud.addItem("")
        self.gridLayout_4.addWidget(self.cbsbaud, 0, 4, 1, 1)
        self.lsbaud = QtWidgets.QLabel(self.Serial)
        self.lsbaud.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lsbaud.setObjectName("lsbaud")
        self.gridLayout_4.addWidget(self.lsbaud, 0, 3, 1, 1)
        self.lsdata = QtWidgets.QLabel(self.Serial)
        self.lsdata.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lsdata.setObjectName("lsdata")
        self.gridLayout_4.addWidget(self.lsdata, 1, 0, 1, 1)
        self.cbsport = QtWidgets.QComboBox(self.Serial)
        self.cbsport.setEditable(True)
        self.cbsport.setObjectName("cbsport")
        self.cbsport.addItem("")
        self.gridLayout_4.addWidget(self.cbsport, 0, 1, 1, 2)
        self.pushButton_open = QtWidgets.QPushButton(self.Serial)
        self.pushButton_open.setObjectName("pushButton_open")
        self.gridLayout_4.addWidget(self.pushButton_open, 2, 4, 1, 1)
        self.cbsdata = QtWidgets.QComboBox(self.Serial)
        self.cbsdata.setEditable(True)
        self.cbsdata.setObjectName("cbsdata")
        self.cbsdata.addItem("")
        self.gridLayout_4.addWidget(self.cbsdata, 1, 1, 1, 2)
        self.Ntrip = QtWidgets.QGroupBox(widget)
        self.Ntrip.setGeometry(QtCore.QRect(599, 119, 231, 159))
        self.Ntrip.setObjectName("Ntrip")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Ntrip)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lncaster = QtWidgets.QLabel(self.Ntrip)
        self.lncaster.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lncaster.setObjectName("lncaster")
        self.gridLayout_2.addWidget(self.lncaster, 0, 0, 1, 1)
        self.comboBox_caster = QtWidgets.QComboBox(self.Ntrip)
        self.comboBox_caster.setEditable(True)
        self.comboBox_caster.setMaxVisibleItems(15)
        self.comboBox_caster.setObjectName("comboBox_caster")
        self.comboBox_caster.addItem("")
        self.comboBox_caster.addItem("")
        self.comboBox_caster.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_caster, 0, 1, 1, 3)
        self.lnport = QtWidgets.QLabel(self.Ntrip)
        self.lnport.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lnport.setObjectName("lnport")
        self.gridLayout_2.addWidget(self.lnport, 1, 0, 1, 1)
        self.comboBox_port = QtWidgets.QComboBox(self.Ntrip)
        self.comboBox_port.setEditable(True)
        self.comboBox_port.setObjectName("comboBox_port")
        self.comboBox_port.addItem("")
        self.comboBox_port.addItem("")
        self.comboBox_port.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_port, 1, 1, 1, 1)
        self.lnmount = QtWidgets.QLabel(self.Ntrip)
        self.lnmount.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lnmount.setObjectName("lnmount")
        self.gridLayout_2.addWidget(self.lnmount, 1, 2, 1, 1)
        self.comboBox_mount = QtWidgets.QComboBox(self.Ntrip)
        self.comboBox_mount.setEditable(True)
        self.comboBox_mount.setObjectName("comboBox_mount")
        self.comboBox_mount.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_mount, 1, 3, 1, 1)
        self.lnuser = QtWidgets.QLabel(self.Ntrip)
        self.lnuser.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lnuser.setObjectName("lnuser")
        self.gridLayout_2.addWidget(self.lnuser, 2, 0, 1, 1)
        self.lineEdit_user = QtWidgets.QLineEdit(self.Ntrip)
        self.lineEdit_user.setAcceptDrops(False)
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.gridLayout_2.addWidget(self.lineEdit_user, 2, 1, 1, 3)
        self.lnpwd = QtWidgets.QLabel(self.Ntrip)
        self.lnpwd.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lnpwd.setObjectName("lnpwd")
        self.gridLayout_2.addWidget(self.lnpwd, 3, 0, 1, 1)
        self.lineEdit_pwd = QtWidgets.QLineEdit(self.Ntrip)
        self.lineEdit_pwd.setAcceptDrops(False)
        self.lineEdit_pwd.setInputMask("")
        self.lineEdit_pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_pwd.setObjectName("lineEdit_pwd")
        self.gridLayout_2.addWidget(self.lineEdit_pwd, 3, 1, 1, 3)
        self.progressBar = QtWidgets.QProgressBar(self.Ntrip)
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 4, 0, 1, 3)
        self.pushButton_conn = QtWidgets.QPushButton(self.Ntrip)
        self.pushButton_conn.setDefault(False)
        self.pushButton_conn.setFlat(False)
        self.pushButton_conn.setObjectName("pushButton_conn")
        self.gridLayout_2.addWidget(self.pushButton_conn, 4, 3, 1, 1)
        self.ATCmd = QtWidgets.QGroupBox(widget)
        self.ATCmd.setGeometry(QtCore.QRect(599, 289, 231, 113))
        self.ATCmd.setObjectName("ATCmd")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ATCmd)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cbatcmd = QtWidgets.QComboBox(self.ATCmd)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.cbatcmd.setFont(font)
        self.cbatcmd.setEditable(True)
        self.cbatcmd.setObjectName("cbatcmd")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.gridLayout_3.addWidget(self.cbatcmd, 0, 0, 1, 1)
        self.pushButton_atcmd = QtWidgets.QPushButton(self.ATCmd)
        self.pushButton_atcmd.setObjectName("pushButton_atcmd")
        self.gridLayout_3.addWidget(self.pushButton_atcmd, 0, 1, 1, 1)
        self.lineEdit_filename = QtWidgets.QLineEdit(self.ATCmd)
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.gridLayout_3.addWidget(self.lineEdit_filename, 1, 0, 1, 1)
        self.open_file = QtWidgets.QPushButton(self.ATCmd)
        self.open_file.setObjectName("open_file")
        self.gridLayout_3.addWidget(self.open_file, 1, 1, 1, 1)
        self.file_transbar = QtWidgets.QProgressBar(self.ATCmd)
        self.file_transbar.setProperty("value", 0)
        self.file_transbar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.file_transbar.setTextVisible(True)
        self.file_transbar.setOrientation(QtCore.Qt.Horizontal)
        self.file_transbar.setInvertedAppearance(False)
        self.file_transbar.setObjectName("file_transbar")
        self.gridLayout_3.addWidget(self.file_transbar, 2, 0, 1, 1)
        self.trans_file = QtWidgets.QPushButton(self.ATCmd)
        self.trans_file.setObjectName("trans_file")
        self.gridLayout_3.addWidget(self.trans_file, 2, 1, 1, 1)
        self.Infos = QtWidgets.QGroupBox(widget)
        self.Infos.setGeometry(QtCore.QRect(9, 409, 581, 130))
        self.Infos.setObjectName("Infos")
        self.gridLayout = QtWidgets.QGridLayout(self.Infos)
        self.gridLayout.setObjectName("gridLayout")
        self.label_13 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 0, 1, 1)
        self.lineEdit_rovlat = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_rovlat.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_rovlat.setReadOnly(True)
        self.lineEdit_rovlat.setObjectName("lineEdit_rovlat")
        self.gridLayout.addWidget(self.lineEdit_rovlat, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 2, 1, 1)
        self.lineEdit_vn = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_vn.setReadOnly(True)
        self.lineEdit_vn.setObjectName("lineEdit_vn")
        self.gridLayout.addWidget(self.lineEdit_vn, 0, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 4, 1, 1)
        self.lineEdit_roll = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_roll.setReadOnly(True)
        self.lineEdit_roll.setObjectName("lineEdit_roll")
        self.gridLayout.addWidget(self.lineEdit_roll, 0, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 6, 1, 1)
        self.lineEdit_time = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_time.setObjectName("lineEdit_time")
        self.gridLayout.addWidget(self.lineEdit_time, 0, 7, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.lineEdit_rovlon = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_rovlon.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_rovlon.setReadOnly(True)
        self.lineEdit_rovlon.setObjectName("lineEdit_rovlon")
        self.gridLayout.addWidget(self.lineEdit_rovlon, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 2, 1, 1)
        self.lineEdit_ve = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_ve.setReadOnly(True)
        self.lineEdit_ve.setObjectName("lineEdit_ve")
        self.gridLayout.addWidget(self.lineEdit_ve, 1, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 4, 1, 1)
        self.lineEdit_pitch = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_pitch.setReadOnly(True)
        self.lineEdit_pitch.setObjectName("lineEdit_pitch")
        self.gridLayout.addWidget(self.lineEdit_pitch, 1, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 6, 1, 1)
        self.lineEdit_wk = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_wk.setObjectName("lineEdit_wk")
        self.gridLayout.addWidget(self.lineEdit_wk, 1, 7, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.lineEdit_rovhgt = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_rovhgt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_rovhgt.setReadOnly(True)
        self.lineEdit_rovhgt.setObjectName("lineEdit_rovhgt")
        self.gridLayout.addWidget(self.lineEdit_rovhgt, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 2, 1, 1)
        self.lineEdit_vu = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_vu.setReadOnly(True)
        self.lineEdit_vu.setObjectName("lineEdit_vu")
        self.gridLayout.addWidget(self.lineEdit_vu, 2, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 4, 1, 1)
        self.lineEdit_yaw = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_yaw.setReadOnly(True)
        self.lineEdit_yaw.setObjectName("lineEdit_yaw")
        self.gridLayout.addWidget(self.lineEdit_yaw, 2, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 6, 1, 1)
        self.lineEdit_sow = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_sow.setObjectName("lineEdit_sow")
        self.gridLayout.addWidget(self.lineEdit_sow, 2, 7, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 3, 0, 1, 1)
        self.lineEdit_solstat = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_solstat.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_solstat.setReadOnly(True)
        self.lineEdit_solstat.setObjectName("lineEdit_solstat")
        self.gridLayout.addWidget(self.lineEdit_solstat, 3, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 3, 2, 1, 1)
        self.lineEdit_dage = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_dage.setReadOnly(True)
        self.lineEdit_dage.setObjectName("lineEdit_dage")
        self.gridLayout.addWidget(self.lineEdit_dage, 3, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 3, 4, 1, 1)
        self.lineEdit_bl = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_bl.setReadOnly(True)
        self.lineEdit_bl.setObjectName("lineEdit_bl")
        self.gridLayout.addWidget(self.lineEdit_bl, 3, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 6, 1, 1)
        self.lineEdit_sats = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_sats.setObjectName("lineEdit_sats")
        self.gridLayout.addWidget(self.lineEdit_sats, 3, 7, 1, 1)
        self.lineEdit_srx = QtWidgets.QLineEdit(widget)
        self.lineEdit_srx.setGeometry(QtCore.QRect(27, 545, 91, 20))
        self.lineEdit_srx.setAutoFillBackground(False)
        self.lineEdit_srx.setReadOnly(True)
        self.lineEdit_srx.setObjectName("lineEdit_srx")
        self.label_srx = QtWidgets.QLabel(widget)
        self.label_srx.setGeometry(QtCore.QRect(9, 545, 16, 16))
        self.label_srx.setObjectName("label_srx")
        self.lineEdit_stx = QtWidgets.QLineEdit(widget)
        self.lineEdit_stx.setGeometry(QtCore.QRect(27, 573, 91, 20))
        self.lineEdit_stx.setReadOnly(True)
        self.lineEdit_stx.setObjectName("lineEdit_stx")
        self.label_stx = QtWidgets.QLabel(widget)
        self.label_stx.setGeometry(QtCore.QRect(9, 571, 16, 16))
        self.label_stx.setObjectName("label_stx")
        self.Extools = QtWidgets.QGroupBox(widget)
        self.Extools.setGeometry(QtCore.QRect(599, 409, 231, 81))
        self.Extools.setObjectName("Extools")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.Extools)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.comboBox_extools = QtWidgets.QComboBox(self.Extools)
        self.comboBox_extools.setEditable(False)
        self.comboBox_extools.setObjectName("comboBox_extools")
        self.comboBox_extools.addItem("")
        self.comboBox_extools.addItem("")
        self.comboBox_extools.addItem("")
        self.comboBox_extools.addItem("")
        self.comboBox_extools.addItem("")
        self.comboBox_extools.addItem("")
        self.comboBox_extools.addItem("")
        self.comboBox_extools.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_extools, 0, 0, 1, 2)
        self.gen_kml = QtWidgets.QPushButton(self.Extools)
        self.gen_kml.setObjectName("gen_kml")
        self.gridLayout_6.addWidget(self.gen_kml, 1, 1, 1, 1)
        self.open_nmea_file = QtWidgets.QPushButton(self.Extools)
        self.open_nmea_file.setObjectName("open_nmea_file")
        self.gridLayout_6.addWidget(self.open_nmea_file, 1, 0, 1, 1)
        self.checkBox_ggafmt = QtWidgets.QCheckBox(widget)
        self.checkBox_ggafmt.setGeometry(QtCore.QRect(171, 548, 65, 16))
        self.checkBox_ggafmt.setMouseTracking(False)
        self.checkBox_ggafmt.setChecked(True)
        self.checkBox_ggafmt.setObjectName("checkBox_ggafmt")
        self.checkBox_autoScoll = QtWidgets.QCheckBox(widget)
        self.checkBox_autoScoll.setGeometry(QtCore.QRect(325, 548, 59, 16))
        self.checkBox_autoScoll.setMouseTracking(False)
        self.checkBox_autoScoll.setCheckable(True)
        self.checkBox_autoScoll.setChecked(True)
        self.checkBox_autoScoll.setObjectName("checkBox_autoScoll")
        self.checkBox_savenmea = QtWidgets.QCheckBox(widget)
        self.checkBox_savenmea.setGeometry(QtCore.QRect(242, 548, 77, 16))
        self.checkBox_savenmea.setMouseTracking(False)
        self.checkBox_savenmea.setChecked(True)
        self.checkBox_savenmea.setObjectName("checkBox_savenmea")
        self.checkBox_logcos = QtWidgets.QCheckBox(widget)
        self.checkBox_logcos.setGeometry(QtCore.QRect(390, 548, 71, 16))
        self.checkBox_logcos.setChecked(True)
        self.checkBox_logcos.setObjectName("checkBox_logcos")
        self.label_fmi = QtWidgets.QLabel(widget)
        self.label_fmi.setGeometry(QtCore.QRect(170, 571, 356, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_fmi.setFont(font)
        self.label_fmi.setOpenExternalLinks(False)
        self.label_fmi.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_fmi.setObjectName("label_fmi")
        self.pushButton_close = QtWidgets.QPushButton(widget)
        self.pushButton_close.setGeometry(QtCore.QRect(756, 560, 73, 23))
        self.pushButton_close.setObjectName("pushButton_close")
        self.pushButton_stop = QtWidgets.QPushButton(widget)
        self.pushButton_stop.setGeometry(QtCore.QRect(678, 560, 72, 23))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.pushButton_clear = QtWidgets.QPushButton(widget)
        self.pushButton_clear.setGeometry(QtCore.QRect(600, 560, 72, 23))
        self.pushButton_clear.setObjectName("pushButton_clear")

        self.retranslateUi(widget)
        self.cbsbaud.setCurrentIndex(4)
        self.cbsdata.setCurrentIndex(0)
        self.comboBox_port.setCurrentIndex(0)
        self.cbatcmd.setCurrentIndex(0)
        self.comboBox_extools.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Trident v1.6 (for any support contact fmi@feyman.cn)"))
        self.textEdit_recv.setHtml(_translate("widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Trident a FMI ntrip serial tool</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">i. Serial</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    -Click &quot;Refresh&quot; button all valid com ports connected to your PC lists in &quot;Port&quot; comb box, set proper baud rate and attributes(in Databits/Parity/Stopbits) then &quot;Open&quot;, serial received data shows in this area.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    -For multi serial interface, click &quot;...&quot; under the &quot;Baud&quot; text.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ii. Ntrip</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    -Set ntrip caster host, port, mount point, user id and password.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    -If you do not know the mount point click &quot;Connect&quot; first, all monut points will list in &quot;Mnt&quot; comb box.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">iii. AT Cmd</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    -Support FMI AT command and H $J cmd.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    -FMI Px series board firmware upgrade.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">iv. Extools</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    -Only support NEMA or $GPFMI to .kml in standard version.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Any bugs or issues feel free to contact fmi@feyman.cn</p></body></html>"))
        self.Serial.setTitle(_translate("widget", "Serial"))
        self.toolButton.setToolTip(_translate("widget", "Multi serial port interface"))
        self.toolButton.setText(_translate("widget", "..."))
        self.pushButton_refresh.setText(_translate("widget", "Refresh"))
        self.lsport.setText(_translate("widget", "Port"))
        self.cbsbaud.setCurrentText(_translate("widget", "115200"))
        self.cbsbaud.setItemText(0, _translate("widget", "4800"))
        self.cbsbaud.setItemText(1, _translate("widget", "9600"))
        self.cbsbaud.setItemText(2, _translate("widget", "19200"))
        self.cbsbaud.setItemText(3, _translate("widget", "57600"))
        self.cbsbaud.setItemText(4, _translate("widget", "115200"))
        self.cbsbaud.setItemText(5, _translate("widget", "230400"))
        self.cbsbaud.setItemText(6, _translate("widget", "460800"))
        self.cbsbaud.setItemText(7, _translate("widget", "921600"))
        self.lsbaud.setText(_translate("widget", "Baud"))
        self.lsdata.setText(_translate("widget", "Attrs"))
        self.cbsport.setCurrentText(_translate("widget", "COM1"))
        self.cbsport.setItemText(0, _translate("widget", "COM1"))
        self.pushButton_open.setText(_translate("widget", "Open"))
        self.cbsdata.setItemText(0, _translate("widget", "8/N/1"))
        self.Ntrip.setTitle(_translate("widget", "Ntrip"))
        self.lncaster.setText(_translate("widget", "Caster"))
        self.comboBox_caster.setItemText(0, _translate("widget", "ntrips.feymani.cn"))
        self.comboBox_caster.setItemText(1, _translate("widget", "219.142.87.107"))
        self.comboBox_caster.setItemText(2, _translate("widget", "219.142.87.73"))
        self.lnport.setText(_translate("widget", "Port"))
        self.comboBox_port.setItemText(0, _translate("widget", "2102"))
        self.comboBox_port.setItemText(1, _translate("widget", "2101"))
        self.comboBox_port.setItemText(2, _translate("widget", "81"))
        self.lnmount.setText(_translate("widget", "Mnt"))
        self.comboBox_mount.setToolTip(_translate("widget", "<html><head/><body><p>drop and click to get mount point</p></body></html>"))
        self.comboBox_mount.setItemText(0, _translate("widget", "Obs"))
        self.lnuser.setText(_translate("widget", "User"))
        self.lineEdit_user.setToolTip(_translate("widget", "<html><head/><body><p>Cause this is a Feynman Innovation ntrip serial tool, default user is feyman-user ofcourse</p></body></html>"))
        self.lineEdit_user.setText(_translate("widget", "feyman-user"))
        self.lnpwd.setText(_translate("widget", "Passwd"))
        self.lineEdit_pwd.setToolTip(_translate("widget", "<html><head/><body><p>password of your current ntrip connection</p></body></html>"))
        self.lineEdit_pwd.setText(_translate("widget", "123456"))
        self.pushButton_conn.setText(_translate("widget", "Connect"))
        self.ATCmd.setTitle(_translate("widget", "AT Cmd"))
        self.cbatcmd.setToolTip(_translate("widget", "<html><head/><body><p>Multi serial port command format: </p><p>AT command &gt; port1,port2</p><p>Example: </p><p>a.AT+THIS_PORT&gt;com2,com3 </p><p>  will send AT+THIS_PORT command to com2 com3</p><p>b.AT+THIS_PORT&gt;all </p><p>  will send AT+THIS_PORT command to all valid port</p></body></html>"))
        self.cbatcmd.setItemText(0, _translate("widget", "AT+THIS_PORT"))
        self.cbatcmd.setItemText(1, _translate("widget", "AT+WARM_RESET"))
        self.cbatcmd.setItemText(2, _translate("widget", "AT+COLD_RESET"))
        self.cbatcmd.setItemText(3, _translate("widget", "AT+READ_PARA"))
        self.cbatcmd.setItemText(4, _translate("widget", "AT+UPDATE_MODE"))
        self.cbatcmd.setItemText(5, _translate("widget", "AT+UPDATE_SHELL"))
        self.cbatcmd.setItemText(6, _translate("widget", "AT+SAVE_ALL"))
        self.cbatcmd.setItemText(7, _translate("widget", "AT+SELF_TEST="))
        self.cbatcmd.setItemText(8, _translate("widget", "AT+GPGGA=UART1,"))
        self.cbatcmd.setItemText(9, _translate("widget", "AT+GPFMI=UART1,"))
        self.cbatcmd.setItemText(10, _translate("widget", "AT+GPRMC=UART1,"))
        self.cbatcmd.setItemText(11, _translate("widget", "AT+GPSAT=UART1,"))
        self.cbatcmd.setItemText(12, _translate("widget", "AT+ZUPT=ENABLE"))
        self.cbatcmd.setItemText(13, _translate("widget", "AT+DR_TIME=120"))
        self.cbatcmd.setItemText(14, _translate("widget", "AT+VEHICLE_MODE="))
        self.cbatcmd.setItemText(15, _translate("widget", "AT+RTCM=UART1,1"))
        self.cbatcmd.setItemText(16, _translate("widget", "AT+BASE_LLH=1,2,3"))
        self.cbatcmd.setItemText(17, _translate("widget", "AT+ACTIVATE_KEY="))
        self.cbatcmd.setItemText(18, _translate("widget", "AT+ALT_PARA=-9.1,37,1"))
        self.cbatcmd.setItemText(19, _translate("widget", "AT+LEVER_ARM=0.01,-0.027,-0.1"))
        self.cbatcmd.setItemText(20, _translate("widget", "$JASC,"))
        self.cbatcmd.setItemText(21, _translate("widget", "$JATT,"))
        self.cbatcmd.setItemText(22, _translate("widget", "$JBAUD,"))
        self.cbatcmd.setItemText(23, _translate("widget", "$JBIN,"))
        self.cbatcmd.setItemText(24, _translate("widget", "$JBOOT,"))
        self.cbatcmd.setItemText(25, _translate("widget", "$JDIFF,"))
        self.cbatcmd.setItemText(26, _translate("widget", "$JNMEA,"))
        self.cbatcmd.setItemText(27, _translate("widget", "$JOFF,"))
        self.cbatcmd.setItemText(28, _translate("widget", "$JPOS,"))
        self.cbatcmd.setItemText(29, _translate("widget", "$JQUERY,"))
        self.cbatcmd.setItemText(30, _translate("widget", "$JRTCM3,"))
        self.cbatcmd.setItemText(31, _translate("widget", "$JRTK,"))
        self.cbatcmd.setItemText(32, _translate("widget", "$JSHOW,"))
        self.pushButton_atcmd.setText(_translate("widget", "Send"))
        self.open_file.setText(_translate("widget", "File"))
        self.trans_file.setText(_translate("widget", "Trans"))
        self.Infos.setTitle(_translate("widget", "States"))
        self.label_13.setText(_translate("widget", "Lat"))
        self.label_14.setText(_translate("widget", "Vn"))
        self.label_15.setText(_translate("widget", "Roll"))
        self.label.setText(_translate("widget", "Time"))
        self.label_10.setText(_translate("widget", "Lon"))
        self.label_11.setText(_translate("widget", "Ve"))
        self.label_12.setText(_translate("widget", "Pitch"))
        self.label_2.setText(_translate("widget", "Wk"))
        self.label_7.setText(_translate("widget", "Alt"))
        self.label_8.setText(_translate("widget", "Vu"))
        self.label_9.setText(_translate("widget", "Yaw"))
        self.label_3.setText(_translate("widget", "Sow"))
        self.label_16.setText(_translate("widget", "Stat"))
        self.label_17.setText(_translate("widget", "dAge"))
        self.label_18.setText(_translate("widget", "BL"))
        self.label_4.setText(_translate("widget", "Sats"))
        self.label_srx.setText(_translate("widget", "Rx"))
        self.label_stx.setText(_translate("widget", "Tx"))
        self.Extools.setTitle(_translate("widget", "Extools"))
        self.comboBox_extools.setToolTip(_translate("widget", "<html><head/><body><p>For more extern tool requirements, please feel free to contact us</p><p>Email:fmi@feyman.cn, Web site:<a href=\"http://www.feymani.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.feymani.com/</span></a></p></body></html>"))
        self.comboBox_extools.setItemText(0, _translate("widget", "1 - Convert nmea to .kml"))
        self.comboBox_extools.setItemText(1, _translate("widget", "2 - Convert fmi to .kml"))
        self.comboBox_extools.setItemText(2, _translate("widget", "3 - NMEA statistics"))
        self.comboBox_extools.setItemText(3, _translate("widget", "4 - Deviation map view"))
        self.comboBox_extools.setItemText(4, _translate("widget", "5 - Ground truth compare"))
        self.comboBox_extools.setItemText(5, _translate("widget", "6 - Receiver obs analysis"))
        self.comboBox_extools.setItemText(6, _translate("widget", "7 - FMI convert"))
        self.comboBox_extools.setItemText(7, _translate("widget", "8 - To be continued..."))
        self.gen_kml.setText(_translate("widget", "Exec"))
        self.open_nmea_file.setText(_translate("widget", "File"))
        self.checkBox_ggafmt.setText(_translate("widget", "GGA Deg"))
        self.checkBox_autoScoll.setText(_translate("widget", "Scroll"))
        self.checkBox_savenmea.setToolTip(_translate("widget", "<html><head/><body><p>record all serial received data in NMEA/*.log</p></body></html>"))
        self.checkBox_savenmea.setText(_translate("widget", "Save NMEA"))
        self.checkBox_logcos.setToolTip(_translate("widget", "<html><head/><body><p>record CORS data in NMEA/*.cors </p></body></html>"))
        self.checkBox_logcos.setText(_translate("widget", "Log CORS"))
        self.label_fmi.setToolTip(_translate("widget", "<html><head/><body><p><br/></p></body></html>"))
        self.label_fmi.setText(_translate("widget", "Developed by Feynman Innovation Development Team "))
        self.pushButton_close.setText(_translate("widget", "Close"))
        self.pushButton_stop.setText(_translate("widget", "Stop"))
        self.pushButton_clear.setText(_translate("widget", "Clear"))
