# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Trident(object):
    def setupUi(self, Trident):
        Trident.setObjectName("Trident")
        Trident.setWindowModality(QtCore.Qt.WindowModal)
        Trident.resize(809, 676)
        self.centralwidget = QtWidgets.QWidget(Trident)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textEdit_recv = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_recv.setMinimumSize(QtCore.QSize(500, 200))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.textEdit_recv.setFont(font)
        self.textEdit_recv.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit_recv.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit_recv.setReadOnly(True)
        self.textEdit_recv.setObjectName("textEdit_recv")
        self.verticalLayout_2.addWidget(self.textEdit_recv)
        self.Infos = QtWidgets.QGroupBox(self.centralwidget)
        self.Infos.setMinimumSize(QtCore.QSize(500, 141))
        self.Infos.setObjectName("Infos")
        self.gridLayout = QtWidgets.QGridLayout(self.Infos)
        self.gridLayout.setObjectName("gridLayout")
        self.label_Y = QtWidgets.QLabel(self.Infos)
        self.label_Y.setObjectName("label_Y")
        self.gridLayout.addWidget(self.label_Y, 3, 10, 1, 1)
        self.lineEdit_sow = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_sow.setReadOnly(True)
        self.lineEdit_sow.setObjectName("lineEdit_sow")
        self.gridLayout.addWidget(self.lineEdit_sow, 3, 13, 1, 1)
        self.label = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 12, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 1, 8, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 5, 1, 1)
        self.lineEdit_time = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_time.setReadOnly(True)
        self.lineEdit_time.setObjectName("lineEdit_time")
        self.gridLayout.addWidget(self.lineEdit_time, 1, 13, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 8, 1, 1)
        self.lineEdit_bl = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_bl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_bl.setReadOnly(True)
        self.lineEdit_bl.setObjectName("lineEdit_bl")
        self.gridLayout.addWidget(self.lineEdit_bl, 4, 9, 1, 1)
        self.lineEdit_rovhgt = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_rovhgt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_rovhgt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_rovhgt.setReadOnly(True)
        self.lineEdit_rovhgt.setObjectName("lineEdit_rovhgt")
        self.gridLayout.addWidget(self.lineEdit_rovhgt, 3, 2, 1, 1)
        self.lineEdit_vn = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_vn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_vn.setReadOnly(True)
        self.lineEdit_vn.setObjectName("lineEdit_vn")
        self.gridLayout.addWidget(self.lineEdit_vn, 1, 6, 1, 1)
        self.lineEdit_yaw = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_yaw.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_yaw.setReadOnly(True)
        self.lineEdit_yaw.setObjectName("lineEdit_yaw")
        self.gridLayout.addWidget(self.lineEdit_yaw, 3, 9, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 4, 5, 1, 1)
        self.lineEdit_rovlat = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_rovlat.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_rovlat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_rovlat.setReadOnly(True)
        self.lineEdit_rovlat.setObjectName("lineEdit_rovlat")
        self.gridLayout.addWidget(self.lineEdit_rovlat, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 0, 1, 1)
        self.lineEdit_solstat = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_solstat.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_solstat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_solstat.setReadOnly(True)
        self.lineEdit_solstat.setObjectName("lineEdit_solstat")
        self.gridLayout.addWidget(self.lineEdit_solstat, 4, 2, 1, 1)
        self.alt_std = QtWidgets.QLineEdit(self.Infos)
        self.alt_std.setObjectName("alt_std")
        self.gridLayout.addWidget(self.alt_std, 3, 4, 1, 1)
        self.p_std = QtWidgets.QLineEdit(self.Infos)
        self.p_std.setObjectName("p_std")
        self.gridLayout.addWidget(self.p_std, 2, 11, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 12, 1, 1)
        self.v_std = QtWidgets.QLineEdit(self.Infos)
        self.v_std.setObjectName("v_std")
        self.gridLayout.addWidget(self.v_std, 4, 4, 1, 1)
        self.lineEdit_wk = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_wk.setReadOnly(True)
        self.lineEdit_wk.setObjectName("lineEdit_wk")
        self.gridLayout.addWidget(self.lineEdit_wk, 2, 13, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 8, 1, 1)
        self.lineEdit_srx = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_srx.setAutoFillBackground(False)
        self.lineEdit_srx.setReadOnly(True)
        self.lineEdit_srx.setObjectName("lineEdit_srx")
        self.gridLayout.addWidget(self.lineEdit_srx, 5, 6, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 12, 1, 1)
        self.lineEdit_sats = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_sats.setReadOnly(True)
        self.lineEdit_sats.setObjectName("lineEdit_sats")
        self.gridLayout.addWidget(self.lineEdit_sats, 4, 13, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 4, 8, 1, 1)
        self.lineEdit_ve = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_ve.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_ve.setReadOnly(True)
        self.lineEdit_ve.setObjectName("lineEdit_ve")
        self.gridLayout.addWidget(self.lineEdit_ve, 2, 6, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 5, 1, 1)
        self.lineEdit_rovlon = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_rovlon.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_rovlon.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_rovlon.setReadOnly(True)
        self.lineEdit_rovlon.setObjectName("lineEdit_rovlon")
        self.gridLayout.addWidget(self.lineEdit_rovlon, 2, 2, 1, 1)
        self.label_srx = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_srx.setFont(font)
        self.label_srx.setObjectName("label_srx")
        self.gridLayout.addWidget(self.label_srx, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 12, 1, 1)
        self.lineEdit_vu = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_vu.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_vu.setReadOnly(True)
        self.lineEdit_vu.setObjectName("lineEdit_vu")
        self.gridLayout.addWidget(self.lineEdit_vu, 3, 6, 1, 1)
        self.lineEdit_stx = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_stx.setReadOnly(True)
        self.lineEdit_stx.setObjectName("lineEdit_stx")
        self.gridLayout.addWidget(self.lineEdit_stx, 5, 2, 1, 1)
        self.lineEdit_pitch = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_pitch.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_pitch.setReadOnly(True)
        self.lineEdit_pitch.setObjectName("lineEdit_pitch")
        self.gridLayout.addWidget(self.lineEdit_pitch, 2, 9, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 4, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.y_std = QtWidgets.QLineEdit(self.Infos)
        self.y_std.setObjectName("y_std")
        self.gridLayout.addWidget(self.y_std, 3, 11, 1, 1)
        self.label_R = QtWidgets.QLabel(self.Infos)
        self.label_R.setObjectName("label_R")
        self.gridLayout.addWidget(self.label_R, 1, 10, 1, 1)
        self.lineEdit_roll = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_roll.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_roll.setReadOnly(True)
        self.lineEdit_roll.setObjectName("lineEdit_roll")
        self.gridLayout.addWidget(self.lineEdit_roll, 1, 9, 1, 1)
        self.r_std = QtWidgets.QLineEdit(self.Infos)
        self.r_std.setObjectName("r_std")
        self.gridLayout.addWidget(self.r_std, 1, 11, 1, 1)
        self.lineEdit_dage = QtWidgets.QLineEdit(self.Infos)
        self.lineEdit_dage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_dage.setReadOnly(True)
        self.lineEdit_dage.setObjectName("lineEdit_dage")
        self.gridLayout.addWidget(self.lineEdit_dage, 4, 6, 1, 1)
        self.label_stx = QtWidgets.QLabel(self.Infos)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_stx.setFont(font)
        self.label_stx.setObjectName("label_stx")
        self.gridLayout.addWidget(self.label_stx, 5, 5, 1, 1)
        self.label_P = QtWidgets.QLabel(self.Infos)
        self.label_P.setObjectName("label_P")
        self.gridLayout.addWidget(self.label_P, 2, 10, 1, 1)
        self.label_v_std = QtWidgets.QLabel(self.Infos)
        self.label_v_std.setObjectName("label_v_std")
        self.gridLayout.addWidget(self.label_v_std, 4, 3, 1, 1)
        self.label_alt = QtWidgets.QLabel(self.Infos)
        self.label_alt.setObjectName("label_alt")
        self.gridLayout.addWidget(self.label_alt, 3, 3, 1, 1)
        self.lon_std = QtWidgets.QLineEdit(self.Infos)
        self.lon_std.setObjectName("lon_std")
        self.gridLayout.addWidget(self.lon_std, 2, 4, 1, 1)
        self.label_lon = QtWidgets.QLabel(self.Infos)
        self.label_lon.setObjectName("label_lon")
        self.gridLayout.addWidget(self.label_lon, 2, 3, 1, 1)
        self.lat_std = QtWidgets.QLineEdit(self.Infos)
        self.lat_std.setObjectName("lat_std")
        self.gridLayout.addWidget(self.lat_std, 1, 4, 1, 1)
        self.label_lat = QtWidgets.QLabel(self.Infos)
        self.label_lat.setObjectName("label_lat")
        self.gridLayout.addWidget(self.label_lat, 1, 3, 1, 1)
        self.widget = QtWidgets.QWidget(self.Infos)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.Infos)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Serial = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Serial.sizePolicy().hasHeightForWidth())
        self.Serial.setSizePolicy(sizePolicy)
        self.Serial.setMinimumSize(QtCore.QSize(0, 120))
        self.Serial.setMaximumSize(QtCore.QSize(260, 120))
        self.Serial.setObjectName("Serial")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Serial)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_4.setContentsMargins(8, 4, 4, 4)
        self.gridLayout_4.setHorizontalSpacing(8)
        self.gridLayout_4.setVerticalSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cbsport = QtWidgets.QComboBox(self.Serial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbsport.sizePolicy().hasHeightForWidth())
        self.cbsport.setSizePolicy(sizePolicy)
        self.cbsport.setMaximumSize(QtCore.QSize(120, 16777215))
        self.cbsport.setEditable(True)
        self.cbsport.setObjectName("cbsport")
        self.cbsport.addItem("")
        self.gridLayout_4.addWidget(self.cbsport, 0, 1, 1, 1)
        self.pushButton_refresh = QtWidgets.QPushButton(self.Serial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_refresh.sizePolicy().hasHeightForWidth())
        self.pushButton_refresh.setSizePolicy(sizePolicy)
        self.pushButton_refresh.setAutoDefault(False)
        self.pushButton_refresh.setDefault(False)
        self.pushButton_refresh.setFlat(False)
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.gridLayout_4.addWidget(self.pushButton_refresh, 1, 2, 1, 1)
        self.cbsbaud = QtWidgets.QComboBox(self.Serial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbsbaud.sizePolicy().hasHeightForWidth())
        self.cbsbaud.setSizePolicy(sizePolicy)
        self.cbsbaud.setEditable(True)
        self.cbsbaud.setInsertPolicy(QtWidgets.QComboBox.InsertBeforeCurrent)
        self.cbsbaud.setObjectName("cbsbaud")
        self.cbsbaud.addItem("")
        self.cbsbaud.addItem("")
        self.cbsbaud.addItem("")
        self.cbsbaud.addItem("")
        self.cbsbaud.addItem("")
        self.cbsbaud.addItem("")
        self.cbsbaud.addItem("")
        self.cbsbaud.addItem("")
        self.gridLayout_4.addWidget(self.cbsbaud, 0, 2, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.Serial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_4.addWidget(self.toolButton, 1, 1, 1, 1)
        self.pushButton_open = QtWidgets.QPushButton(self.Serial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_open.sizePolicy().hasHeightForWidth())
        self.pushButton_open.setSizePolicy(sizePolicy)
        self.pushButton_open.setObjectName("pushButton_open")
        self.gridLayout_4.addWidget(self.pushButton_open, 3, 1, 1, 2)
        self.verticalLayout.addWidget(self.Serial)
        self.Ntrip = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.Ntrip.sizePolicy().hasHeightForWidth())
        self.Ntrip.setSizePolicy(sizePolicy)
        self.Ntrip.setMinimumSize(QtCore.QSize(0, 200))
        self.Ntrip.setMaximumSize(QtCore.QSize(260, 240))
        self.Ntrip.setObjectName("Ntrip")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Ntrip)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_conn = QtWidgets.QPushButton(self.Ntrip)
        self.pushButton_conn.setDefault(False)
        self.pushButton_conn.setFlat(False)
        self.pushButton_conn.setObjectName("pushButton_conn")
        self.gridLayout_2.addWidget(self.pushButton_conn, 5, 2, 1, 1)
        self.lineEdit_pwd = QtWidgets.QLineEdit(self.Ntrip)
        self.lineEdit_pwd.setAcceptDrops(False)
        self.lineEdit_pwd.setInputMask("")
        self.lineEdit_pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_pwd.setObjectName("lineEdit_pwd")
        self.gridLayout_2.addWidget(self.lineEdit_pwd, 4, 1, 1, 2)
        self.lnuser = QtWidgets.QLabel(self.Ntrip)
        self.lnuser.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lnuser.setObjectName("lnuser")
        self.gridLayout_2.addWidget(self.lnuser, 3, 0, 1, 1)
        self.comboBox_caster = QtWidgets.QComboBox(self.Ntrip)
        self.comboBox_caster.setEditable(True)
        self.comboBox_caster.setMaxVisibleItems(15)
        self.comboBox_caster.setObjectName("comboBox_caster")
        self.comboBox_caster.addItem("")
        self.comboBox_caster.addItem("")
        self.comboBox_caster.addItem("")
        self.comboBox_caster.addItem("")
        self.comboBox_caster.addItem("")
        self.comboBox_caster.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_caster, 0, 1, 1, 2)
        self.lnport = QtWidgets.QLabel(self.Ntrip)
        self.lnport.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lnport.setObjectName("lnport")
        self.gridLayout_2.addWidget(self.lnport, 1, 0, 1, 1)
        self.lineEdit_user = QtWidgets.QLineEdit(self.Ntrip)
        self.lineEdit_user.setAcceptDrops(False)
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.gridLayout_2.addWidget(self.lineEdit_user, 3, 1, 1, 2)
        self.progressBar = QtWidgets.QProgressBar(self.Ntrip)
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 5, 0, 1, 2)
        self.lnpwd = QtWidgets.QLabel(self.Ntrip)
        self.lnpwd.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lnpwd.setObjectName("lnpwd")
        self.gridLayout_2.addWidget(self.lnpwd, 4, 0, 1, 1)
        self.comboBox_port = QtWidgets.QComboBox(self.Ntrip)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_port.sizePolicy().hasHeightForWidth())
        self.comboBox_port.setSizePolicy(sizePolicy)
        self.comboBox_port.setEditable(True)
        self.comboBox_port.setObjectName("comboBox_port")
        self.comboBox_port.addItem("")
        self.comboBox_port.addItem("")
        self.comboBox_port.addItem("")
        self.comboBox_port.addItem("")
        self.comboBox_port.addItem("")
        self.comboBox_port.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_port, 1, 1, 1, 2)
        self.lncaster = QtWidgets.QLabel(self.Ntrip)
        self.lncaster.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lncaster.setObjectName("lncaster")
        self.gridLayout_2.addWidget(self.lncaster, 0, 0, 1, 1)
        self.comboBox_mount = QtWidgets.QComboBox(self.Ntrip)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_mount.sizePolicy().hasHeightForWidth())
        self.comboBox_mount.setSizePolicy(sizePolicy)
        self.comboBox_mount.setEditable(True)
        self.comboBox_mount.setObjectName("comboBox_mount")
        self.comboBox_mount.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_mount, 2, 1, 1, 2)
        self.lnmount = QtWidgets.QLabel(self.Ntrip)
        self.lnmount.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lnmount.setObjectName("lnmount")
        self.gridLayout_2.addWidget(self.lnmount, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.Ntrip)
        self.ATCmd = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.ATCmd.sizePolicy().hasHeightForWidth())
        self.ATCmd.setSizePolicy(sizePolicy)
        self.ATCmd.setMinimumSize(QtCore.QSize(0, 0))
        self.ATCmd.setMaximumSize(QtCore.QSize(259, 122))
        self.ATCmd.setObjectName("ATCmd")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ATCmd)
        self.gridLayout_3.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_atcmd = QtWidgets.QPushButton(self.ATCmd)
        self.pushButton_atcmd.setObjectName("pushButton_atcmd")
        self.gridLayout_3.addWidget(self.pushButton_atcmd, 1, 1, 1, 1)
        self.lineEdit_filename = QtWidgets.QLineEdit(self.ATCmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_filename.sizePolicy().hasHeightForWidth())
        self.lineEdit_filename.setSizePolicy(sizePolicy)
        self.lineEdit_filename.setReadOnly(True)
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.gridLayout_3.addWidget(self.lineEdit_filename, 2, 0, 1, 1)
        self.cbatcmd = QtWidgets.QComboBox(self.ATCmd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbatcmd.sizePolicy().hasHeightForWidth())
        self.cbatcmd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.cbatcmd.setFont(font)
        self.cbatcmd.setEditable(True)
        self.cbatcmd.setObjectName("cbatcmd")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.cbatcmd.addItem("")
        self.gridLayout_3.addWidget(self.cbatcmd, 1, 0, 1, 1)
        self.file_transbar = QtWidgets.QProgressBar(self.ATCmd)
        self.file_transbar.setProperty("value", 0)
        self.file_transbar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.file_transbar.setTextVisible(True)
        self.file_transbar.setOrientation(QtCore.Qt.Horizontal)
        self.file_transbar.setInvertedAppearance(False)
        self.file_transbar.setObjectName("file_transbar")
        self.gridLayout_3.addWidget(self.file_transbar, 3, 0, 1, 1)
        self.trans_file = QtWidgets.QPushButton(self.ATCmd)
        self.trans_file.setObjectName("trans_file")
        self.gridLayout_3.addWidget(self.trans_file, 3, 1, 1, 1)
        self.open_file = QtWidgets.QPushButton(self.ATCmd)
        self.open_file.setObjectName("open_file")
        self.gridLayout_3.addWidget(self.open_file, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.ATCmd)
        self.Extools = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Extools.sizePolicy().hasHeightForWidth())
        self.Extools.setSizePolicy(sizePolicy)
        self.Extools.setMinimumSize(QtCore.QSize(0, 0))
        self.Extools.setMaximumSize(QtCore.QSize(260, 79))
        self.Extools.setObjectName("Extools")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.Extools)
        self.gridLayout_6.setContentsMargins(-1, 4, 4, 4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gen_kml = QtWidgets.QPushButton(self.Extools)
        self.gen_kml.setObjectName("gen_kml")
        self.gridLayout_6.addWidget(self.gen_kml, 1, 1, 1, 1)
        self.open_nmea_file = QtWidgets.QPushButton(self.Extools)
        self.open_nmea_file.setObjectName("open_nmea_file")
        self.gridLayout_6.addWidget(self.open_nmea_file, 1, 0, 1, 1)
        self.comboBox_extools = QtWidgets.QComboBox(self.Extools)
        self.comboBox_extools.setEditable(False)
        self.comboBox_extools.setObjectName("comboBox_extools")
        self.comboBox_extools.addItem("")
        self.comboBox_extools.addItem("")
        self.comboBox_extools.addItem("")
        self.comboBox_extools.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_extools, 0, 0, 1, 2)
        self.verticalLayout.addWidget(self.Extools)
        self.rtcm_analysis = QtWidgets.QPushButton(self.centralwidget)
        self.rtcm_analysis.setObjectName("rtcm_analysis")
        self.verticalLayout.addWidget(self.rtcm_analysis)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setEnabled(True)
        self.widget_2.setMaximumSize(QtCore.QSize(16777, 100))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_5.setContentsMargins(4, 0, 2, 2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.checkBox_savenmea = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_savenmea.setMouseTracking(False)
        self.checkBox_savenmea.setChecked(True)
        self.checkBox_savenmea.setObjectName("checkBox_savenmea")
        self.gridLayout_5.addWidget(self.checkBox_savenmea, 1, 2, 1, 1)
        self.checkBox_ggafmt = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_ggafmt.setMouseTracking(False)
        self.checkBox_ggafmt.setChecked(True)
        self.checkBox_ggafmt.setObjectName("checkBox_ggafmt")
        self.gridLayout_5.addWidget(self.checkBox_ggafmt, 1, 1, 1, 1)
        self.checkBox_autoScoll = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_autoScoll.setMouseTracking(False)
        self.checkBox_autoScoll.setCheckable(True)
        self.checkBox_autoScoll.setChecked(True)
        self.checkBox_autoScoll.setObjectName("checkBox_autoScoll")
        self.gridLayout_5.addWidget(self.checkBox_autoScoll, 1, 4, 1, 1)
        self.checkBox_reset = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_reset.setChecked(True)
        self.checkBox_reset.setObjectName("checkBox_reset")
        self.gridLayout_5.addWidget(self.checkBox_reset, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.horizontalLayout.addWidget(self.pushButton_clear)
        self.pushButton_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.horizontalLayout.addWidget(self.pushButton_stop)
        self.pushButton_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout.addWidget(self.pushButton_close)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.setStretch(0, 10)
        self.gridLayout_7.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        Trident.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Trident)
        self.statusbar.setObjectName("statusbar")
        Trident.setStatusBar(self.statusbar)

        self.retranslateUi(Trident)
        self.cbsbaud.setCurrentIndex(4)
        self.comboBox_port.setCurrentIndex(0)
        self.cbatcmd.setCurrentIndex(0)
        self.comboBox_extools.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Trident)

    def retranslateUi(self, Trident):
        _translate = QtCore.QCoreApplication.translate
        self.textEdit_recv.setHtml(_translate("Trident", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Trident a FMI ntrip serial tool</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">i. Serial</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  -Click &quot;Refresh&quot; button all valid com ports connected to your PC lists in &quot;Port&quot; comb box</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  -Set proper baud rate and attributes(in Databits/Parity/Stopbits) </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  -Click &quot;Open&quot; Button and Serial received data shows in this area.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  -For multi serial interface, click &quot;...&quot; under the &quot;COM&quot; Spinner.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ii. Ntrip</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  -Set ntrip caster host, port, mount point, user id and password.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  -If you do not know the mount point click &quot;Connect&quot; first, all monut points will list in &quot;Mnt&quot; comb box.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  -Support Ntrip parameter local record</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">iii. Cmd</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  -Support FMI AT command and H $J cmd.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  -FMI Px series board firmware upgrade.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  -Add AT+VEH_MODE and AT+UAV_MODE cmd</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  -Click &quot;Return&quot; can send cmd order also</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">iv. Extools</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  -Only support NMEA or $GPFMI to .kml in standard version.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Any bugs or issues feel free to contact <span style=\" text-decoration: underline;\">fmi@feyman.cn</span></p></body></html>"))
        self.Infos.setAccessibleName(_translate("Trident", "groupInfos"))
        self.Infos.setTitle(_translate("Trident", "States"))
        self.label_Y.setText(_translate("Trident", "Y σ"))
        self.label.setText(_translate("Trident", "Time"))
        self.label_15.setText(_translate("Trident", "R"))
        self.label_11.setText(_translate("Trident", "Ve"))
        self.label_9.setText(_translate("Trident", "Y"))
        self.lineEdit_bl.setToolTip(_translate("Trident", "base line"))
        self.lineEdit_yaw.setToolTip(_translate("Trident", "yaw(heading) in deg"))
        self.label_17.setText(_translate("Trident", "dAge"))
        self.label_7.setText(_translate("Trident", "Alt"))
        self.label_13.setText(_translate("Trident", "Lat"))
        self.lineEdit_solstat.setToolTip(_translate("Trident", "solution state"))
        self.label_4.setText(_translate("Trident", "Sats"))
        self.label_12.setText(_translate("Trident", "P"))
        self.label_3.setText(_translate("Trident", "ToW"))
        self.label_18.setText(_translate("Trident", "BL"))
        self.label_14.setText(_translate("Trident", "Vn"))
        self.label_8.setText(_translate("Trident", "Vu"))
        self.label_srx.setText(_translate("Trident", "Rx"))
        self.label_2.setText(_translate("Trident", "Wk"))
        self.lineEdit_pitch.setToolTip(_translate("Trident", "pitch in deg"))
        self.label_16.setText(_translate("Trident", "Stat"))
        self.label_10.setText(_translate("Trident", "Lon"))
        self.label_R.setText(_translate("Trident", "R σ"))
        self.lineEdit_roll.setToolTip(_translate("Trident", "roll in deg"))
        self.lineEdit_dage.setToolTip(_translate("Trident", "age of difference"))
        self.label_stx.setText(_translate("Trident", "Tx"))
        self.label_P.setText(_translate("Trident", "P σ"))
        self.label_v_std.setText(_translate("Trident", "vσ"))
        self.label_alt.setText(_translate("Trident", "Alt σ"))
        self.label_lon.setText(_translate("Trident", "Lon σ"))
        self.label_lat.setText(_translate("Trident", "Lat σ"))
        self.Serial.setTitle(_translate("Trident", "Serial"))
        self.cbsport.setCurrentText(_translate("Trident", "COM1"))
        self.cbsport.setItemText(0, _translate("Trident", "COM1"))
        self.pushButton_refresh.setText(_translate("Trident", "Refresh"))
        self.cbsbaud.setCurrentText(_translate("Trident", "115200"))
        self.cbsbaud.setItemText(0, _translate("Trident", "4800"))
        self.cbsbaud.setItemText(1, _translate("Trident", "9600"))
        self.cbsbaud.setItemText(2, _translate("Trident", "19200"))
        self.cbsbaud.setItemText(3, _translate("Trident", "57600"))
        self.cbsbaud.setItemText(4, _translate("Trident", "115200"))
        self.cbsbaud.setItemText(5, _translate("Trident", "230400"))
        self.cbsbaud.setItemText(6, _translate("Trident", "460800"))
        self.cbsbaud.setItemText(7, _translate("Trident", "921600"))
        self.toolButton.setToolTip(_translate("Trident", "Multi serial port interface"))
        self.toolButton.setText(_translate("Trident", "..."))
        self.pushButton_open.setText(_translate("Trident", "Open"))
        self.Ntrip.setTitle(_translate("Trident", "Ntrip"))
        self.pushButton_conn.setText(_translate("Trident", "Connect"))
        self.lineEdit_pwd.setToolTip(_translate("Trident", "<html><head/><body><p>password of your current ntrip connection</p></body></html>"))
        self.lineEdit_pwd.setText(_translate("Trident", "123456"))
        self.lnuser.setText(_translate("Trident", "User"))
        self.comboBox_caster.setItemText(0, _translate("Trident", "ntrips.feymani.cn"))
        self.comboBox_caster.setItemText(1, _translate("Trident", "lab.ntrip.qxwz.com"))
        self.comboBox_caster.setItemText(2, _translate("Trident", "vrs.sixents.com"))
        self.comboBox_caster.setItemText(3, _translate("Trident", "ntrip.mliyadong.com"))
        self.comboBox_caster.setItemText(4, _translate("Trident", "219.142.87.107"))
        self.comboBox_caster.setItemText(5, _translate("Trident", "219.142.87.73"))
        self.lnport.setText(_translate("Trident", "Port"))
        self.lineEdit_user.setToolTip(_translate("Trident", "<html><head/><body><p>Cause this is a Feynman Innovation ntrip serial tool, default user is feyman-user ofcourse</p></body></html>"))
        self.lineEdit_user.setText(_translate("Trident", "feyman-user"))
        self.lnpwd.setText(_translate("Trident", "Passwd"))
        self.comboBox_port.setItemText(0, _translate("Trident", "2102"))
        self.comboBox_port.setItemText(1, _translate("Trident", "2101"))
        self.comboBox_port.setItemText(2, _translate("Trident", "8001"))
        self.comboBox_port.setItemText(3, _translate("Trident", "8002"))
        self.comboBox_port.setItemText(4, _translate("Trident", "8003"))
        self.comboBox_port.setItemText(5, _translate("Trident", "81"))
        self.lncaster.setText(_translate("Trident", "Caster"))
        self.comboBox_mount.setToolTip(_translate("Trident", "<html><head/><body><p>drop and click to get mount point</p></body></html>"))
        self.comboBox_mount.setItemText(0, _translate("Trident", "Source Table"))
        self.lnmount.setText(_translate("Trident", "Mnt"))
        self.ATCmd.setTitle(_translate("Trident", "Cmd"))
        self.pushButton_atcmd.setText(_translate("Trident", "Send"))
        self.cbatcmd.setToolTip(_translate("Trident", "<html><head/><body><p>Multi serial port command format: </p><p>AT command &gt; port1,port2</p><p>Example: </p><p>a.AT+THIS_PORT&gt;com2,com3 </p><p>  will send AT+THIS_PORT command to com2 com3</p><p>b.AT+THIS_PORT&gt;all </p><p>  will send AT+THIS_PORT command to all valid port</p></body></html>"))
        self.cbatcmd.setItemText(0, _translate("Trident", "AT+THIS_PORT"))
        self.cbatcmd.setItemText(1, _translate("Trident", "AT+SAVE_ALL"))
        self.cbatcmd.setItemText(2, _translate("Trident", "AT+WARM_RESET"))
        self.cbatcmd.setItemText(3, _translate("Trident", "AT+COLD_RESET"))
        self.cbatcmd.setItemText(4, _translate("Trident", "AT+READ_PARA"))
        self.cbatcmd.setItemText(5, _translate("Trident", "AT+WORK_MODE=13"))
        self.cbatcmd.setItemText(6, _translate("Trident", "AT+ALIGN_VEL="))
        self.cbatcmd.setItemText(7, _translate("Trident", "AT+DR_TIME=120"))
        self.cbatcmd.setItemText(8, _translate("Trident", "AT+NAVI_RATE="))
        self.cbatcmd.setItemText(9, _translate("Trident", "AT+GPGGA=UART1,"))
        self.cbatcmd.setItemText(10, _translate("Trident", "AT+GPFMI=UART1,"))
        self.cbatcmd.setItemText(11, _translate("Trident", "AT+GPRMC=UART1,"))
        self.cbatcmd.setItemText(12, _translate("Trident", "AT+GPIMU=UART1,"))
        self.cbatcmd.setItemText(13, _translate("Trident", "AT+GPREF=UART1,"))
        self.cbatcmd.setItemText(14, _translate("Trident", "AT+GPSAT=UART1,"))
        self.cbatcmd.setItemText(15, _translate("Trident", "AT+LEVER_ARM=0.01,-0.027,-0.1"))
        self.cbatcmd.setItemText(16, _translate("Trident", "AT+UPDATE_SHELL"))
        self.cbatcmd.setItemText(17, _translate("Trident", "AT+UPDATE_MODE"))
        self.cbatcmd.setItemText(18, _translate("Trident", "AT+SELF_TEST="))
        self.cbatcmd.setItemText(19, _translate("Trident", "AT+VEHICLE_MODE="))
        self.cbatcmd.setItemText(20, _translate("Trident", "AT+RTCM=UART1,1"))
        self.cbatcmd.setItemText(21, _translate("Trident", "AT+BASE_LLH=1,2,3"))
        self.cbatcmd.setItemText(22, _translate("Trident", "AT+ACTIVATE_KEY="))
        self.cbatcmd.setItemText(23, _translate("Trident", "AT+ALT_PARA=-9.1,37,1"))
        self.cbatcmd.setItemText(24, _translate("Trident", "AT+ZUPT=ENABLE"))
        self.trans_file.setText(_translate("Trident", "Trans"))
        self.open_file.setText(_translate("Trident", "File"))
        self.Extools.setTitle(_translate("Trident", "Extools"))
        self.gen_kml.setText(_translate("Trident", "Exec"))
        self.open_nmea_file.setText(_translate("Trident", "File"))
        self.comboBox_extools.setToolTip(_translate("Trident", "<html><head/><body><p>For more extern tool requirements, please feel free to contact us</p><p>Email:fmi@feyman.cn, Web site:<a href=\"http://www.feymani.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.feymani.com/</span></a></p></body></html>"))
        self.comboBox_extools.setItemText(0, _translate("Trident", "1 - Convert nmea to .kml"))
        self.comboBox_extools.setItemText(1, _translate("Trident", "2 - Convert FMI to .kml"))
        self.comboBox_extools.setItemText(2, _translate("Trident", "3 - Convert  U To GGA"))
        self.comboBox_extools.setItemText(3, _translate("Trident", "4 - To be continued..."))
        self.rtcm_analysis.setText(_translate("Trident", "Analysis RTCM"))
        self.checkBox_savenmea.setToolTip(_translate("Trident", "<html><head/><body><p>record all serial received data in NMEA/*.log</p></body></html>"))
        self.checkBox_savenmea.setText(_translate("Trident", "SAVE"))
        self.checkBox_ggafmt.setToolTip(_translate("Trident", "lat lon in degree format"))
        self.checkBox_ggafmt.setText(_translate("Trident", "DEG"))
        self.checkBox_autoScoll.setToolTip(_translate("Trident", "auto scroll"))
        self.checkBox_autoScoll.setText(_translate("Trident", "SCOL"))
        self.checkBox_reset.setToolTip(_translate("Trident", "<html><head/><body><p>record CORS data in NMEA/*.cors </p></body></html>"))
        self.checkBox_reset.setText(_translate("Trident", "RESET"))
        self.pushButton_clear.setText(_translate("Trident", "Clear"))
        self.pushButton_stop.setText(_translate("Trident", "Stop"))
        self.pushButton_close.setText(_translate("Trident", "Close"))
