# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multiser.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Multiser_Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.setWindowModality(QtCore.Qt.WindowModal)
        widget.resize(779, 580)
        widget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Serial_1 = QtWidgets.QGroupBox(widget)
        self.Serial_1.setGeometry(QtCore.QRect(9, 9, 272, 135))
        self.Serial_1.setObjectName("Serial_1")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.Serial_1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_open_1 = QtWidgets.QPushButton(self.Serial_1)
        self.pushButton_open_1.setObjectName("pushButton_open_1")
        self.gridLayout.addWidget(self.pushButton_open_1, 1, 3, 1, 1)
        self.cs_port_1 = QtWidgets.QComboBox(self.Serial_1)
        self.cs_port_1.setStyleSheet("font: 9pt \"SimSun\";")
        self.cs_port_1.setEditable(True)
        self.cs_port_1.setIconSize(QtCore.QSize(8, 8))
        self.cs_port_1.setObjectName("cs_port_1")
        self.cs_port_1.addItem("")
        self.gridLayout.addWidget(self.cs_port_1, 0, 1, 1, 1)
        self.ls_baud_1 = QtWidgets.QLabel(self.Serial_1)
        self.ls_baud_1.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ls_baud_1.setObjectName("ls_baud_1")
        self.gridLayout.addWidget(self.ls_baud_1, 0, 2, 1, 1)
        self.cs_baud_1 = QtWidgets.QComboBox(self.Serial_1)
        self.cs_baud_1.setEditable(True)
        self.cs_baud_1.setInsertPolicy(QtWidgets.QComboBox.InsertBeforeCurrent)
        self.cs_baud_1.setObjectName("cs_baud_1")
        self.cs_baud_1.addItem("")
        self.cs_baud_1.addItem("")
        self.cs_baud_1.addItem("")
        self.cs_baud_1.addItem("")
        self.cs_baud_1.addItem("")
        self.cs_baud_1.addItem("")
        self.cs_baud_1.addItem("")
        self.cs_baud_1.addItem("")
        self.gridLayout.addWidget(self.cs_baud_1, 0, 3, 1, 1)
        self.ls_attr_1 = QtWidgets.QLabel(self.Serial_1)
        self.ls_attr_1.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ls_attr_1.setObjectName("ls_attr_1")
        self.gridLayout.addWidget(self.ls_attr_1, 1, 0, 1, 1)
        self.cs_attrs_1 = QtWidgets.QComboBox(self.Serial_1)
        self.cs_attrs_1.setEditable(True)
        self.cs_attrs_1.setObjectName("cs_attrs_1")
        self.cs_attrs_1.addItem("")
        self.gridLayout.addWidget(self.cs_attrs_1, 1, 1, 1, 1)
        self.cb_firmu1 = QtWidgets.QCheckBox(self.Serial_1)
        self.cb_firmu1.setObjectName("cb_firmu1")
        self.gridLayout.addWidget(self.cb_firmu1, 1, 2, 1, 1)
        self.ls_port_1 = QtWidgets.QLabel(self.Serial_1)
        self.ls_port_1.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ls_port_1.setObjectName("ls_port_1")
        self.gridLayout.addWidget(self.ls_port_1, 0, 0, 1, 1)
        self.ls_stat_1 = QtWidgets.QLabel(self.Serial_1)
        self.ls_stat_1.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ls_stat_1.setObjectName("ls_stat_1")
        self.gridLayout.addWidget(self.ls_stat_1, 2, 0, 1, 1)
        self.ls_lat_1 = QtWidgets.QLabel(self.Serial_1)
        self.ls_lat_1.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ls_lat_1.setObjectName("ls_lat_1")
        self.gridLayout.addWidget(self.ls_lat_1, 4, 0, 1, 1)
        self.lineEdit_llh1 = QtWidgets.QLineEdit(self.Serial_1)
        self.lineEdit_llh1.setToolTip("")
        self.lineEdit_llh1.setReadOnly(True)
        self.lineEdit_llh1.setObjectName("lineEdit_llh1")
        self.gridLayout.addWidget(self.lineEdit_llh1, 4, 1, 1, 3)
        self.lineEdit_stat1 = QtWidgets.QLineEdit(self.Serial_1)
        self.lineEdit_stat1.setToolTip("")
        self.lineEdit_stat1.setReadOnly(True)
        self.lineEdit_stat1.setObjectName("lineEdit_stat1")
        self.gridLayout.addWidget(self.lineEdit_stat1, 2, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.Serial_1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 3, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.Serial_2 = QtWidgets.QGroupBox(widget)
        self.Serial_2.setGeometry(QtCore.QRect(9, 150, 272, 135))
        self.Serial_2.setObjectName("Serial_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.Serial_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cs_baud_2 = QtWidgets.QComboBox(self.Serial_2)
        self.cs_baud_2.setEditable(True)
        self.cs_baud_2.setInsertPolicy(QtWidgets.QComboBox.InsertBeforeCurrent)
        self.cs_baud_2.setObjectName("cs_baud_2")
        self.cs_baud_2.addItem("")
        self.cs_baud_2.addItem("")
        self.cs_baud_2.addItem("")
        self.cs_baud_2.addItem("")
        self.cs_baud_2.addItem("")
        self.cs_baud_2.addItem("")
        self.cs_baud_2.addItem("")
        self.cs_baud_2.addItem("")
        self.gridLayout_3.addWidget(self.cs_baud_2, 0, 3, 1, 1)
        self.ls_attr_2 = QtWidgets.QLabel(self.Serial_2)
        self.ls_attr_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ls_attr_2.setObjectName("ls_attr_2")
        self.gridLayout_3.addWidget(self.ls_attr_2, 1, 0, 1, 1)
        self.ls_baud_2 = QtWidgets.QLabel(self.Serial_2)
        self.ls_baud_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ls_baud_2.setObjectName("ls_baud_2")
        self.gridLayout_3.addWidget(self.ls_baud_2, 0, 2, 1, 1)
        self.cs_attrs_2 = QtWidgets.QComboBox(self.Serial_2)
        self.cs_attrs_2.setEditable(True)
        self.cs_attrs_2.setObjectName("cs_attrs_2")
        self.cs_attrs_2.addItem("")
        self.gridLayout_3.addWidget(self.cs_attrs_2, 1, 1, 1, 1)
        self.pushButton_open_2 = QtWidgets.QPushButton(self.Serial_2)
        self.pushButton_open_2.setObjectName("pushButton_open_2")
        self.gridLayout_3.addWidget(self.pushButton_open_2, 1, 3, 1, 1)
        self.cb_firmu2 = QtWidgets.QCheckBox(self.Serial_2)
        self.cb_firmu2.setObjectName("cb_firmu2")
        self.gridLayout_3.addWidget(self.cb_firmu2, 1, 2, 1, 1)
        self.ls_port_2 = QtWidgets.QLabel(self.Serial_2)
        self.ls_port_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ls_port_2.setObjectName("ls_port_2")
        self.gridLayout_3.addWidget(self.ls_port_2, 0, 0, 1, 1)
        self.cs_port_2 = QtWidgets.QComboBox(self.Serial_2)
        self.cs_port_2.setStyleSheet("font: 9pt \"SimSun\";")
        self.cs_port_2.setEditable(True)
        self.cs_port_2.setIconSize(QtCore.QSize(8, 8))
        self.cs_port_2.setObjectName("cs_port_2")
        self.cs_port_2.addItem("")
        self.gridLayout_3.addWidget(self.cs_port_2, 0, 1, 1, 1)
        self.ls_stat_2 = QtWidgets.QLabel(self.Serial_2)
        self.ls_stat_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ls_stat_2.setObjectName("ls_stat_2")
        self.gridLayout_3.addWidget(self.ls_stat_2, 2, 0, 1, 1)
        self.ls_lat_2 = QtWidgets.QLabel(self.Serial_2)
        self.ls_lat_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ls_lat_2.setObjectName("ls_lat_2")
        self.gridLayout_3.addWidget(self.ls_lat_2, 3, 0, 1, 1)
        self.lineEdit_stat2 = QtWidgets.QLineEdit(self.Serial_2)
        self.lineEdit_stat2.setReadOnly(True)
        self.lineEdit_stat2.setObjectName("lineEdit_stat2")
        self.gridLayout_3.addWidget(self.lineEdit_stat2, 2, 1, 1, 2)
        self.lineEdit_llh2 = QtWidgets.QLineEdit(self.Serial_2)
        self.lineEdit_llh2.setReadOnly(True)
        self.lineEdit_llh2.setObjectName("lineEdit_llh2")
        self.gridLayout_3.addWidget(self.lineEdit_llh2, 3, 1, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.Serial_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 3, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.textEdit_1 = QtWidgets.QTextEdit(widget)
        self.textEdit_1.setGeometry(QtCore.QRect(287, 9, 483, 135))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_1.setFont(font)
        self.textEdit_1.setReadOnly(True)
        self.textEdit_1.setObjectName("textEdit_1")
        self.textEdit_2 = QtWidgets.QTextEdit(widget)
        self.textEdit_2.setGeometry(QtCore.QRect(287, 150, 483, 135))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(widget)
        self.textEdit_3.setGeometry(QtCore.QRect(287, 291, 483, 135))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setReadOnly(True)
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(widget)
        self.textEdit_4.setEnabled(True)
        self.textEdit_4.setGeometry(QtCore.QRect(287, 432, 483, 135))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_4.setFont(font)
        self.textEdit_4.setReadOnly(True)
        self.textEdit_4.setObjectName("textEdit_4")
        self.Serial_3 = QtWidgets.QGroupBox(widget)
        self.Serial_3.setGeometry(QtCore.QRect(9, 291, 272, 135))
        self.Serial_3.setObjectName("Serial_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Serial_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ls_baud_3 = QtWidgets.QLabel(self.Serial_3)
        self.ls_baud_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ls_baud_3.setObjectName("ls_baud_3")
        self.gridLayout_2.addWidget(self.ls_baud_3, 0, 2, 1, 1)
        self.ls_port_3 = QtWidgets.QLabel(self.Serial_3)
        self.ls_port_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ls_port_3.setObjectName("ls_port_3")
        self.gridLayout_2.addWidget(self.ls_port_3, 0, 0, 1, 1)
        self.ls_attr_3 = QtWidgets.QLabel(self.Serial_3)
        self.ls_attr_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ls_attr_3.setObjectName("ls_attr_3")
        self.gridLayout_2.addWidget(self.ls_attr_3, 1, 0, 1, 1)
        self.pushButton_open_3 = QtWidgets.QPushButton(self.Serial_3)
        self.pushButton_open_3.setObjectName("pushButton_open_3")
        self.gridLayout_2.addWidget(self.pushButton_open_3, 1, 3, 1, 1)
        self.ls_lat_3 = QtWidgets.QLabel(self.Serial_3)
        self.ls_lat_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ls_lat_3.setObjectName("ls_lat_3")
        self.gridLayout_2.addWidget(self.ls_lat_3, 4, 0, 1, 1)
        self.cs_attrs_3 = QtWidgets.QComboBox(self.Serial_3)
        self.cs_attrs_3.setEditable(True)
        self.cs_attrs_3.setObjectName("cs_attrs_3")
        self.cs_attrs_3.addItem("")
        self.gridLayout_2.addWidget(self.cs_attrs_3, 1, 1, 1, 1)
        self.cb_firmu3 = QtWidgets.QCheckBox(self.Serial_3)
        self.cb_firmu3.setObjectName("cb_firmu3")
        self.gridLayout_2.addWidget(self.cb_firmu3, 1, 2, 1, 1)
        self.cs_baud_3 = QtWidgets.QComboBox(self.Serial_3)
        self.cs_baud_3.setEditable(True)
        self.cs_baud_3.setInsertPolicy(QtWidgets.QComboBox.InsertBeforeCurrent)
        self.cs_baud_3.setObjectName("cs_baud_3")
        self.cs_baud_3.addItem("")
        self.cs_baud_3.addItem("")
        self.cs_baud_3.addItem("")
        self.cs_baud_3.addItem("")
        self.cs_baud_3.addItem("")
        self.cs_baud_3.addItem("")
        self.cs_baud_3.addItem("")
        self.cs_baud_3.addItem("")
        self.gridLayout_2.addWidget(self.cs_baud_3, 0, 3, 1, 1)
        self.cs_port_3 = QtWidgets.QComboBox(self.Serial_3)
        self.cs_port_3.setStyleSheet("font: 9pt \"SimSun\";")
        self.cs_port_3.setEditable(True)
        self.cs_port_3.setIconSize(QtCore.QSize(8, 8))
        self.cs_port_3.setObjectName("cs_port_3")
        self.cs_port_3.addItem("")
        self.gridLayout_2.addWidget(self.cs_port_3, 0, 1, 1, 1)
        self.ls_stat_3 = QtWidgets.QLabel(self.Serial_3)
        self.ls_stat_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ls_stat_3.setObjectName("ls_stat_3")
        self.gridLayout_2.addWidget(self.ls_stat_3, 2, 0, 1, 1)
        self.lineEdit_stat3 = QtWidgets.QLineEdit(self.Serial_3)
        self.lineEdit_stat3.setReadOnly(True)
        self.lineEdit_stat3.setObjectName("lineEdit_stat3")
        self.gridLayout_2.addWidget(self.lineEdit_stat3, 2, 1, 1, 2)
        self.lineEdit_llh3 = QtWidgets.QLineEdit(self.Serial_3)
        self.lineEdit_llh3.setReadOnly(True)
        self.lineEdit_llh3.setObjectName("lineEdit_llh3")
        self.gridLayout_2.addWidget(self.lineEdit_llh3, 4, 1, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.Serial_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 3, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.Serial_4 = QtWidgets.QGroupBox(widget)
        self.Serial_4.setGeometry(QtCore.QRect(9, 432, 272, 135))
        self.Serial_4.setObjectName("Serial_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.Serial_4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cs_port_4 = QtWidgets.QComboBox(self.Serial_4)
        self.cs_port_4.setStyleSheet("font: 9pt \"SimSun\";")
        self.cs_port_4.setEditable(True)
        self.cs_port_4.setIconSize(QtCore.QSize(8, 8))
        self.cs_port_4.setObjectName("cs_port_4")
        self.cs_port_4.addItem("")
        self.gridLayout_4.addWidget(self.cs_port_4, 0, 1, 1, 1)
        self.cb_firmu4 = QtWidgets.QCheckBox(self.Serial_4)
        self.cb_firmu4.setChecked(False)
        self.cb_firmu4.setObjectName("cb_firmu4")
        self.gridLayout_4.addWidget(self.cb_firmu4, 1, 2, 1, 1)
        self.ls_baud_4 = QtWidgets.QLabel(self.Serial_4)
        self.ls_baud_4.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ls_baud_4.setObjectName("ls_baud_4")
        self.gridLayout_4.addWidget(self.ls_baud_4, 0, 2, 1, 1)
        self.cs_baud_4 = QtWidgets.QComboBox(self.Serial_4)
        self.cs_baud_4.setEditable(True)
        self.cs_baud_4.setInsertPolicy(QtWidgets.QComboBox.InsertBeforeCurrent)
        self.cs_baud_4.setObjectName("cs_baud_4")
        self.cs_baud_4.addItem("")
        self.cs_baud_4.addItem("")
        self.cs_baud_4.addItem("")
        self.cs_baud_4.addItem("")
        self.cs_baud_4.addItem("")
        self.cs_baud_4.addItem("")
        self.cs_baud_4.addItem("")
        self.cs_baud_4.addItem("")
        self.gridLayout_4.addWidget(self.cs_baud_4, 0, 3, 1, 1)
        self.ls_attr_4 = QtWidgets.QLabel(self.Serial_4)
        self.ls_attr_4.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ls_attr_4.setObjectName("ls_attr_4")
        self.gridLayout_4.addWidget(self.ls_attr_4, 1, 0, 1, 1)
        self.ls_lat_4 = QtWidgets.QLabel(self.Serial_4)
        self.ls_lat_4.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ls_lat_4.setObjectName("ls_lat_4")
        self.gridLayout_4.addWidget(self.ls_lat_4, 3, 0, 1, 1)
        self.ls_port_4 = QtWidgets.QLabel(self.Serial_4)
        self.ls_port_4.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ls_port_4.setObjectName("ls_port_4")
        self.gridLayout_4.addWidget(self.ls_port_4, 0, 0, 1, 1)
        self.cs_attrs_4 = QtWidgets.QComboBox(self.Serial_4)
        self.cs_attrs_4.setEditable(True)
        self.cs_attrs_4.setObjectName("cs_attrs_4")
        self.cs_attrs_4.addItem("")
        self.gridLayout_4.addWidget(self.cs_attrs_4, 1, 1, 1, 1)
        self.pushButton_open_4 = QtWidgets.QPushButton(self.Serial_4)
        self.pushButton_open_4.setObjectName("pushButton_open_4")
        self.gridLayout_4.addWidget(self.pushButton_open_4, 1, 3, 1, 1)
        self.ls_stat_4 = QtWidgets.QLabel(self.Serial_4)
        self.ls_stat_4.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ls_stat_4.setObjectName("ls_stat_4")
        self.gridLayout_4.addWidget(self.ls_stat_4, 2, 0, 1, 1)
        self.lineEdit_llh4 = QtWidgets.QLineEdit(self.Serial_4)
        self.lineEdit_llh4.setReadOnly(True)
        self.lineEdit_llh4.setObjectName("lineEdit_llh4")
        self.gridLayout_4.addWidget(self.lineEdit_llh4, 3, 1, 1, 3)
        self.lineEdit_stat4 = QtWidgets.QLineEdit(self.Serial_4)
        self.lineEdit_stat4.setReadOnly(True)
        self.lineEdit_stat4.setObjectName("lineEdit_stat4")
        self.gridLayout_4.addWidget(self.lineEdit_stat4, 2, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.Serial_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 2, 3, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_4, 0, 0, 1, 1)

        self.retranslateUi(widget)
        self.cs_baud_1.setCurrentIndex(4)
        self.cs_baud_2.setCurrentIndex(4)
        self.cs_baud_3.setCurrentIndex(4)
        self.cs_baud_4.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Multi Serial Interface"))
        self.Serial_1.setTitle(_translate("widget", "Serial-Ext1"))
        self.pushButton_open_1.setText(_translate("widget", "Open"))
        self.cs_port_1.setCurrentText(_translate("widget", "COM1"))
        self.cs_port_1.setItemText(0, _translate("widget", "COM1"))
        self.ls_baud_1.setText(_translate("widget", "Baud"))
        self.cs_baud_1.setCurrentText(_translate("widget", "115200"))
        self.cs_baud_1.setItemText(0, _translate("widget", "4800"))
        self.cs_baud_1.setItemText(1, _translate("widget", "9600"))
        self.cs_baud_1.setItemText(2, _translate("widget", "19200"))
        self.cs_baud_1.setItemText(3, _translate("widget", "57600"))
        self.cs_baud_1.setItemText(4, _translate("widget", "115200"))
        self.cs_baud_1.setItemText(5, _translate("widget", "230400"))
        self.cs_baud_1.setItemText(6, _translate("widget", "460800"))
        self.cs_baud_1.setItemText(7, _translate("widget", "921600"))
        self.ls_attr_1.setText(_translate("widget", "Attrs"))
        self.cs_attrs_1.setToolTip(_translate("widget", "data bits/parity check/stop bits"))
        self.cs_attrs_1.setItemText(0, _translate("widget", "8/N/1"))
        self.cb_firmu1.setText(_translate("widget", "FirmU"))
        self.ls_port_1.setText(_translate("widget", "Port"))
        self.ls_stat_1.setText(_translate("widget", "Stats"))
        self.ls_lat_1.setText(_translate("widget", "LLH"))
        self.label.setText(_translate("widget", "empty"))
        self.Serial_2.setTitle(_translate("widget", "Serial-Ext2"))
        self.cs_baud_2.setCurrentText(_translate("widget", "115200"))
        self.cs_baud_2.setItemText(0, _translate("widget", "4800"))
        self.cs_baud_2.setItemText(1, _translate("widget", "9600"))
        self.cs_baud_2.setItemText(2, _translate("widget", "19200"))
        self.cs_baud_2.setItemText(3, _translate("widget", "57600"))
        self.cs_baud_2.setItemText(4, _translate("widget", "115200"))
        self.cs_baud_2.setItemText(5, _translate("widget", "230400"))
        self.cs_baud_2.setItemText(6, _translate("widget", "460800"))
        self.cs_baud_2.setItemText(7, _translate("widget", "921600"))
        self.ls_attr_2.setText(_translate("widget", "Attrs"))
        self.ls_baud_2.setText(_translate("widget", "Baud"))
        self.cs_attrs_2.setToolTip(_translate("widget", "data bits/parity check/stop bits"))
        self.cs_attrs_2.setItemText(0, _translate("widget", "8/N/1"))
        self.pushButton_open_2.setText(_translate("widget", "Open"))
        self.cb_firmu2.setText(_translate("widget", "FirmU"))
        self.ls_port_2.setText(_translate("widget", "Port"))
        self.cs_port_2.setCurrentText(_translate("widget", "COM1"))
        self.cs_port_2.setItemText(0, _translate("widget", "COM1"))
        self.ls_stat_2.setText(_translate("widget", "Stats"))
        self.ls_lat_2.setText(_translate("widget", "LLH"))
        self.label_2.setText(_translate("widget", "empty"))
        self.textEdit_1.setHtml(_translate("widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:8pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Read me plz (too important to ignore):</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">LLH:Latitude, Longitude, Height (degree, degree, meter)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Stats:Time UTC, Number of sats used,  Solution stat, dAge</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">FirmU: check box for firmware updating, the progress of updating will show up in the label</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_2.setHtml(_translate("widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:8pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ok Read me twice plz:</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">LLH:Latitude, Longitude, Height (degree, degree, meter)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Stats:Time UTC, Number of sats used,  Solution stat, dAge</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">FirmU: check box for firmware updating, the progress of updating will show up in the label</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_3.setHtml(_translate("widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:8pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If Matlab can find the answer faster than you  can, then your question is just an algorithm: this is not real problem solving.</p></body></html>"))
        self.textEdit_4.setHtml(_translate("widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:8pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">have a nice day!</p></body></html>"))
        self.Serial_3.setTitle(_translate("widget", "Serial-Ext3"))
        self.ls_baud_3.setText(_translate("widget", "Baud"))
        self.ls_port_3.setText(_translate("widget", "Port"))
        self.ls_attr_3.setText(_translate("widget", "Attrs"))
        self.pushButton_open_3.setText(_translate("widget", "Open"))
        self.ls_lat_3.setText(_translate("widget", "LLH"))
        self.cs_attrs_3.setToolTip(_translate("widget", "data bits/parity check/stop bits"))
        self.cs_attrs_3.setItemText(0, _translate("widget", "8/N/1"))
        self.cb_firmu3.setText(_translate("widget", "FirmU"))
        self.cs_baud_3.setCurrentText(_translate("widget", "115200"))
        self.cs_baud_3.setItemText(0, _translate("widget", "4800"))
        self.cs_baud_3.setItemText(1, _translate("widget", "9600"))
        self.cs_baud_3.setItemText(2, _translate("widget", "19200"))
        self.cs_baud_3.setItemText(3, _translate("widget", "57600"))
        self.cs_baud_3.setItemText(4, _translate("widget", "115200"))
        self.cs_baud_3.setItemText(5, _translate("widget", "230400"))
        self.cs_baud_3.setItemText(6, _translate("widget", "460800"))
        self.cs_baud_3.setItemText(7, _translate("widget", "921600"))
        self.cs_port_3.setCurrentText(_translate("widget", "COM1"))
        self.cs_port_3.setItemText(0, _translate("widget", "COM1"))
        self.ls_stat_3.setText(_translate("widget", "Stats"))
        self.label_3.setText(_translate("widget", "empty"))
        self.Serial_4.setTitle(_translate("widget", "Serial-Ext4"))
        self.cs_port_4.setCurrentText(_translate("widget", "COM1"))
        self.cs_port_4.setItemText(0, _translate("widget", "COM1"))
        self.cb_firmu4.setText(_translate("widget", "FirmU"))
        self.ls_baud_4.setText(_translate("widget", "Baud"))
        self.cs_baud_4.setCurrentText(_translate("widget", "115200"))
        self.cs_baud_4.setItemText(0, _translate("widget", "4800"))
        self.cs_baud_4.setItemText(1, _translate("widget", "9600"))
        self.cs_baud_4.setItemText(2, _translate("widget", "19200"))
        self.cs_baud_4.setItemText(3, _translate("widget", "57600"))
        self.cs_baud_4.setItemText(4, _translate("widget", "115200"))
        self.cs_baud_4.setItemText(5, _translate("widget", "230400"))
        self.cs_baud_4.setItemText(6, _translate("widget", "460800"))
        self.cs_baud_4.setItemText(7, _translate("widget", "921600"))
        self.ls_attr_4.setText(_translate("widget", "Attrs"))
        self.ls_lat_4.setText(_translate("widget", "LLH"))
        self.ls_port_4.setText(_translate("widget", "Port"))
        self.cs_attrs_4.setToolTip(_translate("widget", "data bits/parity check/stop bits"))
        self.cs_attrs_4.setItemText(0, _translate("widget", "8/N/1"))
        self.pushButton_open_4.setText(_translate("widget", "Open"))
        self.ls_stat_4.setText(_translate("widget", "Stats"))
        self.label_4.setText(_translate("widget", "empty"))
