# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ntrip.py.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ntripDialog(object):
    def setupUi(self, ntripDialog):
        ntripDialog.setObjectName("ntripDialog")
        ntripDialog.resize(320, 184)
        ntripDialog.setMaximumSize(QtCore.QSize(320, 184))
        self.gridLayout_3 = QtWidgets.QGridLayout(ntripDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(ntripDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(ntripDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.ip = QtWidgets.QComboBox(ntripDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ip.sizePolicy().hasHeightForWidth())
        self.ip.setSizePolicy(sizePolicy)
        self.ip.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ip.setEditable(True)
        self.ip.setObjectName("ip")
        self.ip.addItem("")
        self.gridLayout_2.addWidget(self.ip, 1, 0, 1, 1)
        self.port = QtWidgets.QComboBox(ntripDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.port.sizePolicy().hasHeightForWidth())
        self.port.setSizePolicy(sizePolicy)
        self.port.setMaximumSize(QtCore.QSize(100, 16777215))
        self.port.setEditable(True)
        self.port.setObjectName("port")
        self.port.addItem("")
        self.port.addItem("")
        self.port.addItem("")
        self.port.addItem("")
        self.gridLayout_2.addWidget(self.port, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.username = QtWidgets.QLineEdit(ntripDialog)
        self.username.setObjectName("username")
        self.gridLayout.addWidget(self.username, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(ntripDialog)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.pwd = QtWidgets.QLineEdit(ntripDialog)
        self.pwd.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwd.setObjectName("pwd")
        self.gridLayout.addWidget(self.pwd, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(ntripDialog)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(ntripDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.mountPoint = QtWidgets.QLineEdit(ntripDialog)
        self.mountPoint.setObjectName("mountPoint")
        self.gridLayout.addWidget(self.mountPoint, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(ntripDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 2, 0, 1, 1)

        self.retranslateUi(ntripDialog)
        self.buttonBox.accepted.connect(ntripDialog.accept)
        self.buttonBox.rejected.connect(ntripDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ntripDialog)

    def retranslateUi(self, ntripDialog):
        _translate = QtCore.QCoreApplication.translate
        ntripDialog.setWindowTitle(_translate("ntripDialog", "Dialog"))
        self.label.setText(_translate("ntripDialog", "Ip"))
        self.label_2.setText(_translate("ntripDialog", "port"))
        self.ip.setCurrentText(_translate("ntripDialog", "ntrips.feymani.cn"))
        self.ip.setItemText(0, _translate("ntripDialog", "ntrips.feymani.cn"))
        self.port.setCurrentText(_translate("ntripDialog", "2102"))
        self.port.setItemText(0, _translate("ntripDialog", "2102"))
        self.port.setItemText(1, _translate("ntripDialog", "8001"))
        self.port.setItemText(2, _translate("ntripDialog", "8002"))
        self.port.setItemText(3, _translate("ntripDialog", "8003"))
        self.label_4.setText(_translate("ntripDialog", "username"))
        self.pwd.setText(_translate("ntripDialog", "123456"))
        self.label_3.setText(_translate("ntripDialog", "mountpoint"))
        self.label_5.setText(_translate("ntripDialog", "password"))
