# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotdialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlotView(object):
    def setupUi(self, PlotView):
        PlotView.setObjectName("PlotView")
        PlotView.resize(652, 560)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PlotView.sizePolicy().hasHeightForWidth())
        PlotView.setSizePolicy(sizePolicy)
        PlotView.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLayout = QtWidgets.QGridLayout(PlotView)
        self.gridLayout.setContentsMargins(6, 6, 6, 6)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setContentsMargins(-1, -1, 4, 0)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.typeSelect = QtWidgets.QComboBox(PlotView)
        self.typeSelect.setEditable(False)
        self.typeSelect.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.typeSelect.setFrame(True)
        self.typeSelect.setObjectName("typeSelect")
        self.typeSelect.addItem("")
        self.typeSelect.addItem("")
        self.typeSelect.addItem("")
        self.horizontalLayout.addWidget(self.typeSelect)
        self.stateSelect = QtWidgets.QComboBox(PlotView)
        self.stateSelect.setEnabled(False)
        self.stateSelect.setEditable(False)
        self.stateSelect.setObjectName("stateSelect")
        self.stateSelect.addItem("")
        self.stateSelect.addItem("")
        self.stateSelect.addItem("")
        self.stateSelect.addItem("")
        self.stateSelect.addItem("")
        self.stateSelect.addItem("")
        self.horizontalLayout.addWidget(self.stateSelect)
        self.inputType = QtWidgets.QComboBox(PlotView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputType.sizePolicy().hasHeightForWidth())
        self.inputType.setSizePolicy(sizePolicy)
        self.inputType.setObjectName("inputType")
        self.inputType.addItem("")
        self.inputType.addItem("")
        self.horizontalLayout.addWidget(self.inputType)
        self.dataPath = QtWidgets.QLineEdit(PlotView)
        self.dataPath.setObjectName("dataPath")
        self.horizontalLayout.addWidget(self.dataPath)
        self.toolButton = QtWidgets.QToolButton(PlotView)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.refreshView = QtWidgets.QPushButton(PlotView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refreshView.sizePolicy().hasHeightForWidth())
        self.refreshView.setSizePolicy(sizePolicy)
        self.refreshView.setMinimumSize(QtCore.QSize(10, 10))
        self.refreshView.setMaximumSize(QtCore.QSize(68, 35))
        self.refreshView.setStyleSheet("")
        self.refreshView.setObjectName("refreshView")
        self.horizontalLayout.addWidget(self.refreshView)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.widget = QtWidgets.QWidget(PlotView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.messagebox = QtWidgets.QLabel(PlotView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messagebox.sizePolicy().hasHeightForWidth())
        self.messagebox.setSizePolicy(sizePolicy)
        self.messagebox.setText("")
        self.messagebox.setObjectName("messagebox")
        self.horizontalLayout_3.addWidget(self.messagebox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setContentsMargins(-1, -1, 6, -1)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(PlotView)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label = QtWidgets.QLabel(PlotView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(0)
        self.label.setMidLineWidth(1)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(PlotView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("background-color: rgb(89, 247, 255);")
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(PlotView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setStyleSheet("background-color: rgb(34, 255, 35);")
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(PlotView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet("background-color: rgb(9, 52, 255);")
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(PlotView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setStyleSheet("background-color: rgb(255, 242, 11);")
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_5.setLineWidth(0)
        self.label_5.setMidLineWidth(1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.refresh = QtWidgets.QPushButton(PlotView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refresh.sizePolicy().hasHeightForWidth())
        self.refresh.setSizePolicy(sizePolicy)
        self.refresh.setObjectName("refresh")
        self.horizontalLayout_3.addWidget(self.refresh)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(PlotView)
        QtCore.QMetaObject.connectSlotsByName(PlotView)

    def retranslateUi(self, PlotView):
        _translate = QtCore.QCoreApplication.translate
        PlotView.setWindowTitle(_translate("PlotView", "PlotView"))
        self.typeSelect.setItemText(0, _translate("PlotView", "GndTrk"))
        self.typeSelect.setItemText(1, _translate("PlotView", "Position"))
        self.typeSelect.setItemText(2, _translate("PlotView", "State"))
        self.stateSelect.setItemText(0, _translate("PlotView", "Q=ALL"))
        self.stateSelect.setItemText(1, _translate("PlotView", "Q=1"))
        self.stateSelect.setItemText(2, _translate("PlotView", "Q=2"))
        self.stateSelect.setItemText(3, _translate("PlotView", "Q=4"))
        self.stateSelect.setItemText(4, _translate("PlotView", "Q=5"))
        self.stateSelect.setItemText(5, _translate("PlotView", "Q=6"))
        self.inputType.setItemText(0, _translate("PlotView", "Serial"))
        self.inputType.setItemText(1, _translate("PlotView", "File"))
        self.toolButton.setText(_translate("PlotView", "..."))
        self.refreshView.setText(_translate("PlotView", "refresh"))
        self.label_6.setText(_translate("PlotView", "FixState："))
        self.label.setText(_translate("PlotView", "1"))
        self.label_2.setText(_translate("PlotView", "2"))
        self.label_3.setText(_translate("PlotView", "4"))
        self.label_4.setText(_translate("PlotView", "5"))
        self.label_5.setText(_translate("PlotView", "6"))
        self.refresh.setText(_translate("PlotView", "clear"))
