# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Server.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NtripTool(object):
    def setupUi(self, NtripTool):
        NtripTool.setObjectName("NtripTool")
        NtripTool.resize(394, 302)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NtripTool.sizePolicy().hasHeightForWidth())
        NtripTool.setSizePolicy(sizePolicy)
        NtripTool.setMaximumSize(QtCore.QSize(430, 302))
        self.gridLayout_3 = QtWidgets.QGridLayout(NtripTool)
        self.gridLayout_3.setContentsMargins(8, 8, 8, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.group_io = QtWidgets.QGroupBox(NtripTool)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_io.sizePolicy().hasHeightForWidth())
        self.group_io.setSizePolicy(sizePolicy)
        self.group_io.setMaximumSize(QtCore.QSize(3000, 300))
        self.group_io.setTitle("")
        self.group_io.setObjectName("group_io")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.group_io)
        self.gridLayout_2.setContentsMargins(8, 8, 8, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_16 = QtWidgets.QLabel(self.group_io)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 2, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.group_io)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 1, 1, 1)
        self.outputType1 = QtWidgets.QComboBox(self.group_io)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputType1.sizePolicy().hasHeightForWidth())
        self.outputType1.setSizePolicy(sizePolicy)
        self.outputType1.setMaximumSize(QtCore.QSize(120, 16777215))
        self.outputType1.setEditable(True)
        self.outputType1.setCurrentText("")
        self.outputType1.setObjectName("outputType1")
        self.outputType1.addItem("")
        self.outputType1.setItemText(0, "")
        self.outputType1.addItem("")
        self.outputType1.addItem("")
        self.gridLayout.addWidget(self.outputType1, 2, 2, 1, 1)
        self.inputType = QtWidgets.QComboBox(self.group_io)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputType.sizePolicy().hasHeightForWidth())
        self.inputType.setSizePolicy(sizePolicy)
        self.inputType.setMaximumSize(QtCore.QSize(120, 16777215))
        self.inputType.setEditable(True)
        self.inputType.setObjectName("inputType")
        self.inputType.addItem("")
        self.inputType.addItem("")
        self.gridLayout.addWidget(self.inputType, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.group_io)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.group_io)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(10, 10))
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_4.setLineWidth(1)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.group_io)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 1, 4, 1, 1)
        self.inputOpt = QtWidgets.QPushButton(self.group_io)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputOpt.sizePolicy().hasHeightForWidth())
        self.inputOpt.setSizePolicy(sizePolicy)
        self.inputOpt.setMaximumSize(QtCore.QSize(50, 16777215))
        self.inputOpt.setObjectName("inputOpt")
        self.gridLayout.addWidget(self.inputOpt, 1, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.group_io)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.group_io)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 1, 1, 1)
        self.inputState = QtWidgets.QLabel(self.group_io)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputState.sizePolicy().hasHeightForWidth())
        self.inputState.setSizePolicy(sizePolicy)
        self.inputState.setMaximumSize(QtCore.QSize(10, 10))
        self.inputState.setFrameShape(QtWidgets.QFrame.Box)
        self.inputState.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inputState.setLineWidth(1)
        self.inputState.setText("")
        self.inputState.setObjectName("inputState")
        self.gridLayout.addWidget(self.inputState, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.group_io)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 3, 1, 1)
        self.outputState1 = QtWidgets.QLabel(self.group_io)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputState1.sizePolicy().hasHeightForWidth())
        self.outputState1.setSizePolicy(sizePolicy)
        self.outputState1.setMaximumSize(QtCore.QSize(10, 10))
        self.outputState1.setFrameShape(QtWidgets.QFrame.Box)
        self.outputState1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputState1.setLineWidth(1)
        self.outputState1.setText("")
        self.outputState1.setObjectName("outputState1")
        self.gridLayout.addWidget(self.outputState1, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.group_io)
        self.label_7.setTextFormat(QtCore.Qt.RichText)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.outputOpt1 = QtWidgets.QPushButton(self.group_io)
        self.outputOpt1.setObjectName("outputOpt1")
        self.gridLayout.addWidget(self.outputOpt1, 2, 3, 1, 1)
        self.outputType2 = QtWidgets.QComboBox(self.group_io)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputType2.sizePolicy().hasHeightForWidth())
        self.outputType2.setSizePolicy(sizePolicy)
        self.outputType2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.outputType2.setEditable(True)
        self.outputType2.setCurrentText("")
        self.outputType2.setObjectName("outputType2")
        self.outputType2.addItem("")
        self.outputType2.setItemText(0, "")
        self.outputType2.addItem("")
        self.outputType2.addItem("")
        self.gridLayout.addWidget(self.outputType2, 3, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.group_io)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 1, 1, 1)
        self.outputState2 = QtWidgets.QLabel(self.group_io)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputState2.sizePolicy().hasHeightForWidth())
        self.outputState2.setSizePolicy(sizePolicy)
        self.outputState2.setMaximumSize(QtCore.QSize(10, 10))
        self.outputState2.setFrameShape(QtWidgets.QFrame.Box)
        self.outputState2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputState2.setLineWidth(1)
        self.outputState2.setText("")
        self.outputState2.setObjectName("outputState2")
        self.gridLayout.addWidget(self.outputState2, 3, 0, 1, 1)
        self.outputOpt2 = QtWidgets.QPushButton(self.group_io)
        self.outputOpt2.setObjectName("outputOpt2")
        self.gridLayout.addWidget(self.outputOpt2, 3, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.group_io)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 3, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.group_io)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 2, 0, 1, 1)
        self.stateLabel = QtWidgets.QLabel(self.group_io)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stateLabel.sizePolicy().hasHeightForWidth())
        self.stateLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.stateLabel.setFont(font)
        self.stateLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.stateLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stateLabel.setText("")
        self.stateLabel.setTextFormat(QtCore.Qt.MarkdownText)
        self.stateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stateLabel.setObjectName("stateLabel")
        self.gridLayout_2.addWidget(self.stateLabel, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.group_io, 0, 0, 1, 1)
        self.horizontalGroupBox = QtWidgets.QGroupBox(NtripTool)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalGroupBox.sizePolicy().hasHeightForWidth())
        self.horizontalGroupBox.setSizePolicy(sizePolicy)
        self.horizontalGroupBox.setMaximumSize(QtCore.QSize(3008, 50))
        self.horizontalGroupBox.setObjectName("horizontalGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startBtn = QtWidgets.QPushButton(self.horizontalGroupBox)
        self.startBtn.setObjectName("startBtn")
        self.horizontalLayout.addWidget(self.startBtn)
        self.OptionBtn = QtWidgets.QPushButton(self.horizontalGroupBox)
        self.OptionBtn.setObjectName("OptionBtn")
        self.horizontalLayout.addWidget(self.OptionBtn)
        self.ShowInfoBtn = QtWidgets.QPushButton(self.horizontalGroupBox)
        self.ShowInfoBtn.setObjectName("ShowInfoBtn")
        self.horizontalLayout.addWidget(self.ShowInfoBtn)
        self.gridLayout_3.addWidget(self.horizontalGroupBox, 1, 0, 1, 1)

        self.retranslateUi(NtripTool)
        QtCore.QMetaObject.connectSlotsByName(NtripTool)

    def retranslateUi(self, NtripTool):
        _translate = QtCore.QCoreApplication.translate
        NtripTool.setWindowTitle(_translate("NtripTool", "Form"))
        self.label_8.setText(_translate("NtripTool", "Output"))
        self.outputType1.setItemText(1, _translate("NtripTool", "NtripServer"))
        self.outputType1.setItemText(2, _translate("NtripTool", "File"))
        self.inputType.setCurrentText(_translate("NtripTool", "Serial"))
        self.inputType.setItemText(0, _translate("NtripTool", "Serial"))
        self.inputType.setItemText(1, _translate("NtripTool", "NtripClient"))
        self.label_12.setText(_translate("NtripTool", "Output"))
        self.inputOpt.setText(_translate("NtripTool", "..."))
        self.label_14.setText(_translate("NtripTool", "Bps"))
        self.label_6.setText(_translate("NtripTool", "Input"))
        self.label_10.setText(_translate("NtripTool", "Option"))
        self.label_7.setText(_translate("NtripTool", "Type"))
        self.outputOpt1.setText(_translate("NtripTool", "..."))
        self.outputType2.setItemText(1, _translate("NtripTool", "NtripServer"))
        self.outputType2.setItemText(2, _translate("NtripTool", "File"))
        self.label_9.setText(_translate("NtripTool", "Streams"))
        self.outputOpt2.setText(_translate("NtripTool", "..."))
        self.startBtn.setText(_translate("NtripTool", "Start"))
        self.OptionBtn.setText(_translate("NtripTool", "Option"))
        self.ShowInfoBtn.setText(_translate("NtripTool", "Show Info"))
